INTERFACE
FUNCTION DATASTREAM(BUFRTYPE,BUFRSUBTYPE,&
 &   GEN_CENTRE,GEN_SUBCENTRE,SATID)

USE PARKIND1  ,ONLY : JPRD

IMPLICIT NONE

REAL(KIND=JPRD)   :: DATASTREAM

REAL(KIND=JPRD), INTENT(IN)   :: BUFRTYPE
REAL(KIND=JPRD), INTENT(IN)   :: BUFRSUBTYPE
REAL(KIND=JPRD), INTENT(IN)   :: GEN_CENTRE
REAL(KIND=JPRD), INTENT(IN)   :: GEN_SUBCENTRE
REAL(KIND=JPRD), INTENT(IN)   :: SATID
END FUNCTION
END INTERFACE
