SUBROUTINE CMOCTMAP(CDMAP  ,KOUT   ,KOBTYP ,KCDTYP ,KOTSQNO,KCDSQNO )

!**** SUBROUTINE CMOCTMAP - MAP CMA OBSERVATION AND CODE TYPES

!        D. VASILJEVIC    ECMWF    01/09/1994

!     PURPOSE
!     -------

!        MAP CMA OBSERVATION AND CODE TYPE INTO SEQUENCE NOS.

!**   INTERFACE
!     ---------

!        CALL CMOCTMAP(CDMAP  ,KOUT   ,
!                      KOBTYP ,KCDTYP ,
!                      KOTSQNO,KCDSQNO )
!     WHERE:
!           CDMAP   = MAP EITHER CMA/BUFR INTO SEQUENCE NO. OR THE
!                     OTHER WAY ROUND
!           KOUT    = OUTPUT UNIT
!           KOBTYP  = OBS. TYPE
!           KCDTYP  = OBS. CODE TYPE
!           KOTSQNO = OBS. TYPE SEQUENCE NO.
!           KCDSQNO = OBS. CODE TYPE SEQUENCE NO.

!        CMOCTMAP IS CALLED BY

!**   METHOD
!     ------

!        FOR EACH OBS. AND CODE TYPE WITHIN AN OBS. TYPE A SIMPLE 
!     SEQUENCE NO. IS ASSIGNED.

!**   EXTERNALS
!     ---------

!        ENDRUN - ABORT

!**   MODIFICATIONS
!     -------------
!        Niels Bormann  23/12/2004  RARAD becomes LIMB; new codetypes for LIMB
!        Anne Fouilloux 31/03/2010 Add a new codetype for MERIS data (NTCWC)
!        Anne Fouilloux 29/07/2010 Add new codetype for GBRAD data
!        Patricia de Rosnay 16/05/2011 Add new codetype for Additional Land Data
!        M. Rennie      03/06/2011 Add obstype for LIDAR and move DWL
!        Saleh Abdalla  16/06/2011 Add new codetype for RADAR ALTIMETER data
!        Antje Inness   22/09/2011 Add new observation type for in-situ atm. composition data (ISAC)
!        A. Geer        03-Jan-2012 New obstype for all-sky satellite radiances
!        T. Kral        28-Jan-2014 New codetypes for TAMDAR, ACARS with mixing ratio,
!                       BUFR PILOT and BUFR SYNOP
!-----------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK

USE YOMCOCTP , ONLY : NSYNOP   ,NSYNOPSQ ,NSRSCD   ,NSRSCDSQ ,&
 & NATSCD   ,NATSCDSQ ,NSHSCD   ,NSHSCDSQ ,NABSCD   ,&
 & NABSCDSQ ,NSHRED   ,NSHREDSQ ,NATSHS   ,NATSHSSQ ,&
 & NAIREP   ,NAIREPSQ ,NAIRCD   ,NAIRCDSQ ,NCODAR   ,&
 & NCODARSQ ,NCOLBA   ,NCOLBASQ ,NAMDAR   ,NAMDARSQ ,&
 & NACARS   ,NACARSSQ ,NSIMAI   ,NSIMAISQ ,NSATOB   ,&
 & NSATOBSQ ,NSTBCD   ,NSTBCDSQ ,NSTB86   ,NSTB86SQ ,&
 & NSTB87   ,NSTB87SQ ,NADSCD   ,NADSCDSQ,&
 & NSST     ,NSSTSQ   ,NDRIBU   ,NDRIBUSQ ,NDRBCD   ,&
 & NDRBCDSQ ,NBATHY   ,NBATHYSQ ,NTESAC   ,NTESACSQ ,&
 & NDERS1   ,NDERS1SQ ,NTEMP    ,NTEMPSQ  ,NLDTCD   ,&
 & NLDTCDSQ ,NSHTCD   ,NSHTCDSQ ,NTDROP   ,NTDROPSQ ,&
 & NROCOB   ,NROCOBSQ ,NROCSH   ,NROCSHSQ ,NMBTMP   ,&
 & NMBTMPSQ ,NSIMTE   ,NSIMTESQ ,NLBTEM   ,NLBTEMSQ ,&
 & NSBTEM   ,NSBTEMSQ ,NDBTEM   ,NDBTEMSQ ,NFBTEM   ,NFBTEMSQ ,&
 & NPILOT   ,NPILOTSQ ,&
 & NLDPCD   ,NLDPCDSQ ,NSHPCD   ,NSHPCDSQ ,NWPPCD   ,&
 & NWPPCDSQ ,&
 & NSATEM   ,NSATEMSQ ,NSTMCD   ,NSTMCDSQ ,&
 & NSTOVS   ,NSTOVSSQ ,NSTRESAT   ,NSTRESATSQ ,&
 & NSTDWL,&
 & NSTDWLSQ ,NSTTOV   ,NSTTOVSQ ,NGTSTB   ,NGTSTBSQ ,&
 & NGTST1   ,NGTST1SQ ,NGTST2   ,NGTST2SQ ,NGTHRB   ,&
 & NGTHRBSQ ,NGTHR1   ,NGTHR1SQ ,NGTHR2   ,NGTHR2SQ ,&
 & NSSMI    ,NSSMISQ  ,&
 & NPAOB    ,NPAOBSQ  ,NPABCD   ,NPABCDSQ ,NSCATT   ,&
 & NSCATTSQ ,NSCAT1   ,NSCAT1SQ ,NSCAT2   ,NSCAT2SQ ,&
 & NSCAT3   ,NSCAT3SQ ,NLIMB    ,NLIMBSQ  ,&
 & NSYRCD   ,NSYRCDSQ ,NSCAT4   ,NSCAT4SQ ,&
 & NSCAT5   ,NSCAT5SQ ,NSCAT6   ,NSCAT6SQ ,&
 & NSCAT7   ,NSCAT7SQ ,NSCAT8   ,NSCAT8SQ ,&
 & NEWPPCD  ,NEWPPCDSQ,NJWPPCD  ,NJWPPCDSQ          ,&
 & NRADOH   ,NRADOHSQ ,NTYPHO   ,NTYPHOSQ           ,&
 & NMETAR   ,NMETARSQ ,NPGPS    ,NPGPSSQ            ,&
 & NGPSRO   ,NGPSROSQ ,NLRAD    ,NLRADSQ            ,&
 & NRADAR   ,NRADARSQ ,NRADA1   ,NRADA1SQ           ,&
 & NSMOS    ,NSMOSSQ  , NTCWC   , NTCWCSQ           ,&
 & NGBRAD   ,NGBRADSQ ,NRADRR   ,NRADRRSQ           ,&
 & NISAC    ,NISACSQ  ,NISAC1   ,NISAC1SQ           ,&
 & NLIDAR   ,NLIDARSQ ,NDWLPCD  ,NDWLPCDSQ          ,&
 & NRALT    ,NRALTSQ  ,NRALT1   ,NRALT1SQ ,NRALT2   ,&
 & NRALT2SQ ,NRALT3   ,NRALT3SQ ,NRALT4   ,NRALT4SQ ,&
 & NRALT5   ,NRALT5SQ ,NALLSKY  ,NALLSKYSQ          ,&
 & NIMSIMS  ,NIMSIMSSQ,&
 & NRAINGG  ,NRAINGGSQ,&
 & NTAMDAR  ,NTAMDARSQ,NACARSMR ,NACARSMRSQ,&
 & NMDEHS   ,NMDEHSSQ ,NAADSC   ,NAADSCSQ  ,&
 & NBLDPCD  ,NBLDPCDSQ,NBSHPCD  ,NBSHPCDSQ ,&
 & NBLSCD   ,NBLSCDSQ ,NBSSCD   ,NBSSCDSQ  ,&
 & NWAMDAR  ,NWAMDARSQ,NBUOYM   ,NBUOYMSQ  ,&
 & NBUOYD   ,NBUOYDSQ

IMPLICIT NONE

CHARACTER(LEN=*)  ,INTENT(IN)    :: CDMAP 
INTEGER(KIND=JPIM),INTENT(IN)    :: KOUT 
INTEGER(KIND=JPIM),INTENT(IN)    :: KOBTYP 
INTEGER(KIND=JPIM),INTENT(IN)    :: KCDTYP 
INTEGER(KIND=JPIM),INTENT(INOUT) :: KOTSQNO 
INTEGER(KIND=JPIM),INTENT(INOUT) :: KCDSQNO 
REAL(KIND=JPRB) :: ZHOOK_HANDLE

#include "abortdb.intfb.h"

!*
!-----------------------------------------------------------------------

!        1.        MAP CMA OBS. AND CODE TYPE INTO SEQUENCE NO.
!                  --------------------------------------------

IF (LHOOK) CALL DR_HOOK('CMOCTMAP',0,ZHOOK_HANDLE)
IF(CDMAP == 'CODETOSQ' )       THEN

!*          1.1    SYNOP

  IF(KOBTYP == NSYNOP)           THEN
    KOTSQNO = NSYNOPSQ

!*          1.1.1  SYNOP LAND REPORT

    IF(KCDTYP == NSRSCD)           THEN
      KCDSQNO = NSRSCDSQ

!*          1.1.2  SYNOP LAND AUTOMATIC REPORT

    ELSEIF(KCDTYP == NATSCD)      THEN
      KCDSQNO = NATSCDSQ

!*          1.1.3  SYNOP-SHIP REPORT

    ELSEIF(KCDTYP == NSHSCD)      THEN
      KCDSQNO = NSHSCDSQ

!*          1.1.4  SYNOP-SHIP ABBREVIATED REPORT

    ELSEIF(KCDTYP == NABSCD)      THEN
      KCDSQNO = NABSCDSQ

!*          1.1.5  SYNOP SHRED REPORT

    ELSEIF(KCDTYP == NSHRED)      THEN
      KCDSQNO = NSHREDSQ

!*          1.1.6  SYNOP AUTOMATIC SHIP REPORT

    ELSEIF(KCDTYP == NATSHS)      THEN
      KCDSQNO = NATSHSSQ

!*          1.1.7  FRENCH SYNOP AUTOMATIC LAND REPORT

    ELSEIF(KCDTYP == NSYRCD)      THEN
      KCDSQNO = NSYRCDSQ

!*          1.1.8  FRENCH radome

    ELSEIF(KCDTYP == NRADOH)      THEN
      KCDSQNO = NRADOHSQ

!*          1.1.9  METAR

    ELSEIF(KCDTYP == NMETAR)      THEN
      KCDSQNO = NMETARSQ

!*          1.1.10 Ground-based GPS

    ELSEIF(KCDTYP == NPGPS)      THEN
      KCDSQNO = NPGPSSQ

!*          1.1.11  ADDITIONAL LAND REPORT

    ELSEIF(KCDTYP == NADSCD)      THEN
      KCDSQNO = NADSCDSQ

!*          1.1.12  BUFR LAND SYNOP REPORT

    ELSEIF(KCDTYP == NBLSCD)      THEN
      KCDSQNO = NBLSCDSQ

!*          1.1.13  BUFR Ship SYNOP REPORT

    ELSEIF(KCDTYP == NBSSCD)      THEN
      KCDSQNO = NBSSCDSQ

!*          1.1.14  UNKNOWN CMA CODE TYPE

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP'')')
      WRITE(KOUT,'('' UNKNOWN CMA CODE TYPE'')')
      WRITE(KOUT,'('' CMA OBS. TYPE:'',I10)') KOBTYP
      WRITE(KOUT,'('' CMA CODE TYPE:'',I10)') KCDTYP
      CALL ABORTDB('CMOCTMAP','UNKNOWN CMA CODE TYPE',KCDTYP)
    ENDIF

!*          1.2    AIREP

  ELSEIF(KOBTYP == NAIREP)      THEN
    KOTSQNO = NAIREPSQ

!*          1.2.1  AIRCRAFT REPORT

    IF(KCDTYP == NAIRCD)           THEN
      KCDSQNO = NAIRCDSQ

!*          1.2.2  CODAR REPORT

    ELSEIF(KCDTYP == NCODAR)       THEN
      KCDSQNO = NCODARSQ

!*          1.2.3  COLBA REPORT

    ELSEIF(KCDTYP == NCOLBA)       THEN
      KCDSQNO = NCOLBASQ

!*          1.2.4  AMDAR AIRCRAFT REPORT

    ELSEIF(KCDTYP == NAMDAR)       THEN
      KCDSQNO = NAMDARSQ

!*          1.2.5  ACARS AIRCRAFT REPORT

    ELSEIF(KCDTYP == NACARS)       THEN
      KCDSQNO = NACARSSQ

!*          1.2.6  SIMULATED AIREP REPORT

    ELSEIF(KCDTYP == NSIMAI)       THEN
      KCDSQNO = NSIMAISQ

!*          1.2.7  TAMDAR AIRCRAFT REPORT

    ELSEIF(KCDTYP == NTAMDAR)      THEN
      KCDSQNO = NTAMDARSQ

!*          1.2.8  ACARS WITH MIXING RATIO

    ELSEIF(KCDTYP == NACARSMR)     THEN
      KCDSQNO = NACARSMRSQ

!*          1.2.9  WIGOS AMDAR AIRCRAFT REPORT

    ELSEIF(KCDTYP == NWAMDAR)     THEN
      KCDSQNO = NWAMDARSQ

!*          1.2.10  MODE-S EHS AIRCRAFT REPORT

    ELSEIF(KCDTYP == NMDEHS)     THEN
      KCDSQNO = NMDEHSSQ

!*          1.2.11  ADS-C AIRCRAFT REPORT

    ELSEIF(KCDTYP == NAADSC)     THEN
      KCDSQNO = NAADSCSQ

!*          1.2.12 UNKNOWN CMA CODE TYPE

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP'')')
      WRITE(KOUT,'('' UNKNOWN CMA CODE TYPE'')')
      WRITE(KOUT,'('' CMA OBS. TYPE:'',I10)') KOBTYP
      WRITE(KOUT,'('' CMA CODE TYPE:'',I10)') KCDTYP
      CALL ABORTDB('CMOCTMAP','UNKNOWN CMA CODE TYPE',KCDTYP)
    ENDIF

!*          1.3    SATOB

  ELSEIF(KOBTYP == NSATOB)       THEN
    KOTSQNO = NSATOBSQ

!*          1.3.1  SATOB REPORT

    IF(KCDTYP == NSTBCD)            THEN
      KCDSQNO = NSTBCDSQ

!*          1.3.2  HIGH RES. VIS WIND SATOB REPORT

    ELSEIF(KCDTYP == NSTB86)            THEN
      KCDSQNO = NSTB86SQ

!*          1.3.3  SST REPORT

    ELSEIF(KCDTYP == NSST  )       THEN
      KCDSQNO = NSSTSQ

!*          1.3.4  AMV SATOB REPORT

    ELSEIF(KCDTYP == NSTB87)            THEN
      KCDSQNO = NSTB87SQ

!*          1.3.9  UNKNOWN CMA CODE TYPE

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP'')')
      WRITE(KOUT,'('' UNKNOWN CMA CODE TYPE'')')
      WRITE(KOUT,'('' CMA OBS. TYPE:'',I10)') KOBTYP
      WRITE(KOUT,'('' CMA CODE TYPE:'',I10)') KCDTYP
      CALL ABORTDB('CMOCTMAP','UNKNOWN CMA CODE TYPE',KCDTYP)
    ENDIF

!*          1.4    DRIBU

  ELSEIF(KOBTYP == NDRIBU)       THEN
    KOTSQNO = NDRIBUSQ

!*          1.4.1  DRIBU REPORT

    IF(KCDTYP == NDRBCD)            THEN
      KCDSQNO = NDRBCDSQ

!*          1.4.2  BATHY REPORT

    ELSEIF(KCDTYP == NBATHY)       THEN
      KCDSQNO = NBATHYSQ

!*          1.4.3  TESAC REPORT

    ELSEIF(KCDTYP == NTESAC)       THEN
      KCDSQNO = NTESACSQ

!*          1.4.4  ERS1 AS DRIBU

    ELSEIF(KCDTYP == NDERS1)       THEN
      KCDSQNO = NDERS1SQ

!*          1.4.5  MOORED BUOY REPORT

    ELSEIF(KCDTYP == NBUOYM)       THEN
      KCDSQNO = NBUOYMSQ

!*          1.4.6  DRIFTING BUOY REPORT

    ELSEIF(KCDTYP == NBUOYD)       THEN
      KCDSQNO = NBUOYDSQ

!*          1.4.9  UNKNOWN CMA CODE TYPE

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP'')')
      WRITE(KOUT,'('' UNKNOWN CMA CODE TYPE:'')')
      WRITE(KOUT,'('' CMA OBS. TYPE:'',I10)') KOBTYP
      WRITE(KOUT,'('' CMA CODE TYPE:'',I10)') KCDTYP
      CALL ABORTDB('CMOCTMAP','UNKNOWN CMA CODE TYPE',KCDTYP)
    ENDIF

!*          1.5    TEMP

  ELSEIF(KOBTYP == NTEMP )       THEN
    KOTSQNO = NTEMPSQ

!*          1.5.1  LAND TEMP REPORT

    IF(KCDTYP == NLDTCD)            THEN
      KCDSQNO = NLDTCDSQ

!*          1.5.2  TEMP SHIP REPORT

    ELSEIF(KCDTYP == NSHTCD)       THEN
      KCDSQNO = NSHTCDSQ

!*          1.5.3  TEMP-DROP REPORT

    ELSEIF(KCDTYP == NTDROP)       THEN
      KCDSQNO = NTDROPSQ

!*          1.5.4  ROCOB REPORT

    ELSEIF(KCDTYP == NROCOB)       THEN
      KCDSQNO = NROCOBSQ

!*          1.5.5  ROCOB SHIP REPORT

    ELSEIF(KCDTYP == NROCSH)       THEN
      KCDSQNO = NROCSHSQ

!*          1.5.6  MOBILE TEMP REPORT

    ELSEIF(KCDTYP == NMBTMP)       THEN
      KCDSQNO = NMBTMPSQ

!*          1.5.7  SIMULATED TEMP STATION CODE TYPE

    ELSEIF(KCDTYP == NSIMTE)       THEN
      KCDSQNO = NSIMTESQ

!*          1.5.8  BUFR Land TEMP

    ELSEIF(KCDTYP == NLBTEM)       THEN
      KCDSQNO = NLBTEMSQ

!*          1.5.9  BUFR Ship TEMP

    ELSEIF(KCDTYP == NSBTEM)       THEN
      KCDSQNO = NSBTEMSQ

!*          1.5.10 BUFR TEMP DROP

    ELSEIF(KCDTYP == NDBTEM)       THEN
      KCDSQNO = NDBTEMSQ

!*          1.5.11 BUFR TEMP DESCENT

    ELSEIF(KCDTYP == NFBTEM)       THEN
      KCDSQNO = NFBTEMSQ

!*          1.5.12 UNKNOWN CMA CODE TYPE

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP'')')
      WRITE(KOUT,'('' UNKNOWN CMA CODE TYPE:'')')
      WRITE(KOUT,'('' CMA OBS. TYPE:'',I10)') KOBTYP
      WRITE(KOUT,'('' CMA CODE TYPE:'',I10)') KCDTYP
      CALL ABORTDB('CMOCTMAP','UNKNOWN CMA CODE TYPE',KCDTYP)
    ENDIF

!*          1.6    PILOT

  ELSEIF(KOBTYP == NPILOT)       THEN
    KOTSQNO = NPILOTSQ

!*          1.6.1  LAND PILOT REPORT

    IF(KCDTYP == NLDPCD)            THEN
      KCDSQNO = NLDPCDSQ

!*          1.6.2  SHIP PILOT REPORT

    ELSEIF(KCDTYP == NSHPCD)       THEN
      KCDSQNO = NSHPCDSQ

!*          1.6.3  AMERICAN WIND PROFILERS

    ELSEIF(KCDTYP == NWPPCD)       THEN
      KCDSQNO = NWPPCDSQ

!*          1.6.4  EUROPEAN WIND PROFILERS

    ELSEIF(KCDTYP == NEWPPCD)       THEN
      KCDSQNO = NEWPPCDSQ

!*          1.6.5  JAPANESE WIND PROFILERS

    ELSEIF(KCDTYP == NJWPPCD)       THEN
      KCDSQNO = NJWPPCDSQ

!*          1.6.6  BUFR LAND PILOT REPORT

    ELSEIF(KCDTYP == NBLDPCD)       THEN
      KCDSQNO = NBLDPCDSQ

!*          1.6.7  BUFR SHIP PILOT REPORT

    ELSEIF(KCDTYP == NBSHPCD)       THEN
      KCDSQNO = NBSHPCDSQ

!*          1.6.6a  MOBILE WIND PILOT - OBSOLETE

!    ELSEIF(KCDTYP == NMBPLT)       THEN
!      KCDSQNO = NMBPLTSQ

!*          1.6.9  UNKNOWN CMA CODE TYPE

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP'')')
      WRITE(KOUT,'('' UNKNOWN CMA CODE TYPE'')')
      WRITE(KOUT,'('' CMA OBS. TYPE:'',I10)') KOBTYP
      WRITE(KOUT,'('' CMA CODE TYPE:'',I10)') KCDTYP
      CALL ABORTDB('CMOCTMAP','UNKNOWN CMA CODE TYPE',KCDTYP)
    ENDIF

!*          1.7    SATEM

  ELSEIF(KOBTYP == NSATEM)       THEN
    KOTSQNO = NSATEMSQ

!*          1.7.1  SATEM REPORT

    IF(KCDTYP == NSTMCD)            THEN
      KCDSQNO = NSTMCDSQ

!*          1.7.2  HIGH RESOLUTION SATTELITE REPORT

    ELSEIF(KCDTYP == NSTOVS)       THEN
      KCDSQNO = NSTOVSSQ

!*          1.7.3  HIGH RESOLUTION SIMULATED DWL SATELLITE REPORT

    ELSEIF(KCDTYP == NSTDWL)       THEN
      KCDSQNO = NSTDWLSQ

!*          1.7.4  HIGH RESOLUTION SIMULATED TOVS SATELLITE REPORT

    ELSEIF(KCDTYP == NSTTOV)       THEN
      KCDSQNO = NSTTOVSQ

!*          1.7.5  GTS BUFR SATEM REPORT
!                  (250 KM TEMP AND HUM PROFILES)

    ELSEIF(KCDTYP == NGTSTB)       THEN
      KCDSQNO = NGTSTBSQ

!*          1.7.6  GTS BUFR SATEM CLEAR RADIANCE REPORT

    ELSEIF(KCDTYP == NGTST1)       THEN
      KCDSQNO = NGTST1SQ

!*          1.7.7  GTS BUFR SATEM RETR PROFILES AND
!                  CLEAR RADIANCES REPORT

    ELSEIF(KCDTYP == NGTST2)       THEN
      KCDSQNO = NGTST2SQ

!*          1.7.8  HIGH RES 80 KM BUFR NON GTS SATEM RETR PROFILES

    ELSEIF(KCDTYP == NGTHRB)       THEN
      KCDSQNO = NGTHRBSQ

!*          1.7.9  HIGH RES 80 KM BUFR NON GTS SATEM CLEAR
!                  RADIANCE REPORT

    ELSEIF(KCDTYP == NGTHR1)       THEN
      KCDSQNO = NGTHR1SQ

!*          1.7.10 HIGH RES 80 KM BUFR NON GTS SATEM PROFILES AND
!                  CLEAR RADIANCE REPORT

    ELSEIF(KCDTYP == NGTHR2)       THEN
      KCDSQNO = NGTHR2SQ

!*          1.7.11 RETRIEVED ATMOSPHERIC PARAMETER REPORT
!*                 INCLUDES: Ozone, CHEM variables,
!*                 AEROSOL observations (AOD, RAO, RFA, ODA) and
!*                 CLOUD OPTICAL DEPTH 

    ELSEIF(KCDTYP == NSTRESAT )       THEN
      KCDSQNO = NSTRESATSQ

!*          1.7.12 SMOS

    ELSEIF(KCDTYP == NSMOS )       THEN
      KCDSQNO = NSMOSSQ

!*          1.7.13 MERIS

    ELSEIF(KCDTYP == NTCWC )       THEN
      KCDSQNO = NTCWCSQ

!*          1.7.14 UNKNOWN CMA CODE TYPE

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP'')')
      WRITE(KOUT,'('' UNKNOWN CMA CODE TYPE'')')
      WRITE(KOUT,'('' CMA OBS. TYPE:'',I10)') KOBTYP
      WRITE(KOUT,'('' CMA CODE TYPE:'',I10)') KCDTYP
      CALL ABORTDB('CMOCTMAP','UNKNOWN CMA CODE TYPE',KCDTYP)
    ENDIF

!*          1.8    PAOB

  ELSEIF(KOBTYP == NPAOB )       THEN
    KOTSQNO = NPAOBSQ

!*          1.8.1  PAOB REPORT

    IF(KCDTYP == NPABCD)            THEN
      KCDSQNO = NPABCDSQ

!*          1.8.2  donnees cyclone

    ELSEIF(KCDTYP == NTYPHO)            THEN
      KCDSQNO = NTYPHOSQ

!*          1.8.9  UNKNOWN CMA CODE TYPE

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP'')')
      WRITE(KOUT,'('' UNKNOWN CMA CODE TYPE'')')
      WRITE(KOUT,'('' CMA OBS. TYPE:'',I10)') KOBTYP
      WRITE(KOUT,'('' CMA CODE TYPE:'',I10)') KCDTYP
      CALL ABORTDB('CMOCTMAP','UNKNOWN CMA CODE TYPE',KCDTYP)
    ENDIF

!*          1.9    SCATTEROMETER

  ELSEIF(KOBTYP == NSCATT)       THEN
    KOTSQNO = NSCATTSQ

!*          1.9.1  SCATTEROMETER CODE 1

    IF(KCDTYP == NSCAT1)            THEN
      KCDSQNO = NSCAT1SQ

!*          1.9.2  SCATTEROMETER CODE 2

    ELSEIF(KCDTYP == NSCAT2)            THEN
      KCDSQNO = NSCAT2SQ

!*          1.9.3  SCATTEROMETER CODE 3

    ELSEIF(KCDTYP == NSCAT3)            THEN
      KCDSQNO = NSCAT3SQ

!*          1.9.4  SCATTEROMETER CODE 4

    ELSEIF(KCDTYP == NSCAT4)            THEN
      KCDSQNO = NSCAT4SQ

!*          1.9.5  SCATTEROMETER CODE 5

    ELSEIF(KCDTYP == NSCAT5)            THEN
      KCDSQNO = NSCAT5SQ

!*          1.9.6  SCATTEROMETER CODE 6

    ELSEIF(KCDTYP == NSCAT6)            THEN
      KCDSQNO = NSCAT6SQ

!*          1.9.7  SCATTEROMETER CODE 7

    ELSEIF(KCDTYP == NSCAT7)            THEN
      KCDSQNO = NSCAT7SQ

!*          1.9.8  SCATTEROMETER CODE 8

    ELSEIF(KCDTYP == NSCAT8)            THEN
      KCDSQNO = NSCAT8SQ
      
!*          1.9.7  UNKNOWN CMA CODE TYPE

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP'')')
      WRITE(KOUT,'('' UNKNOWN CMA CODE TYPE'')')
      WRITE(KOUT,'('' CMA OBS. TYPE:'',I10)') KOBTYP
      WRITE(KOUT,'('' CMA CODE TYPE:'',I10)') KCDTYP
      CALL ABORTDB('CMOCTMAP','UNKNOWN CMA CODE TYPE',KCDTYP)
    ENDIF

!*          1.10   LIMB OBSERVATIONS

  ELSEIF(KOBTYP == NLIMB)       THEN
    KOTSQNO = NLIMBSQ

!*          1.10.1 GPS RO

    IF(KCDTYP == NGPSRO)            THEN
      KCDSQNO = NGPSROSQ

!*          1.10.2 Limb radiances

    ELSEIF(KCDTYP == NLRAD)            THEN
      KCDSQNO = NLRADSQ

!*          1.10.9 UNKNOWN CMA CODE TYPE

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP'')')
      WRITE(KOUT,'('' UNKNOWN CMA CODE TYPE'')')
      WRITE(KOUT,'('' CMA OBS. TYPE:'',I10)') KOBTYP
      WRITE(KOUT,'('' CMA CODE TYPE:'',I10)') KCDTYP
      CALL ABORTDB('CMOCTMAP','UNKNOWN CMA CODE TYPE',KCDTYP)
    ENDIF

!*          1.11 ISAC: In-situ atmospheric composition (ECMWF)
 
  ELSEIF(KOBTYP == NISAC) THEN
    KOTSQNO = NISACSQ

!*          1.11.1 BUFR IAGOS aircraft data (ISAC 1)

    IF(KCDTYP == NISAC1)  THEN
      KCDSQNO = NISAC1SQ
    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP'')')
      WRITE(KOUT,'('' UNKNOWN CMA CODE TYPE'')')
      WRITE(KOUT,'('' CMA OBS. TYPE:'',I10)') KOBTYP
      WRITE(KOUT,'('' CMA CODE TYPE:'',I10)') KCDTYP
      CALL ABORTDB('CMOCTMAP','UNKNOWN CMA CODE TYPE',KCDTYP)
    ENDIF

!*          1.11.9 UNKNOWN CMA CODE TYPE

    ELSEIF(KOBTYP == 11) THEN
      KOTSQNO  = 11

!*          1.12   RADAR ALTIMETER

  ELSEIF(KOBTYP == NRALT )       THEN
    KOTSQNO = NRALTSQ

!*          1.12.1 RADAR ALTIMETER CODE 1

    IF(KCDTYP == NRALT1)            THEN
      KCDSQNO = NRALT1SQ

!*          1.12.2 RADAR ALTIMETER CODE 2

    ELSEIF(KCDTYP == NRALT2)            THEN
      KCDSQNO = NRALT2SQ

!*          1.12.3 RADAR ALTIMETER CODE 3

    ELSEIF(KCDTYP == NRALT3)            THEN
      KCDSQNO = NRALT3SQ

!*          1.12.4 RADAR ALTIMETER CODE 4

    ELSEIF(KCDTYP == NRALT4)            THEN
      KCDSQNO = NRALT4SQ

!*          1.12.5 RADAR ALTIMETER CODE 5

    ELSEIF(KCDTYP == NRALT5)            THEN
      KCDSQNO = NRALT5SQ

!*          1.12.6 UNKNOWN CMA CODE TYPE

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP'')')
      WRITE(KOUT,'('' UNKNOWN RADAR ALTIMETER CMA CODE TYPE'')')
      WRITE(KOUT,'('' CMA OBS. TYPE:'',I10)') KOBTYP
      WRITE(KOUT,'('' CMA CODE TYPE:'',I10)') KCDTYP
      CALL ABORTDB('CMOCTMAP','UNKNOWN RADAR ALTIMETER CMA CODE TYPE',KCDTYP)
    ENDIF

!*          1.13 RADAR

    ELSEIF(KOBTYP == NRADAR) THEN 
      KOTSQNO = NRADARSQ

!*          1.13.1 BUFR RADAR REFLECTIVITY 1

    IF(KCDTYP == NRADA1)  THEN 
      KCDSQNO = NRADA1SQ

!*          1.13.9 UNKNOWN CMA CODE TYPE

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP'')')
      WRITE(KOUT,'('' UNKNOWN CMA CODE TYPE'')')
      WRITE(KOUT,'('' CMA OBS. TYPE:'',I10)') KOBTYP
      WRITE(KOUT,'('' CMA CODE TYPE:'',I10)') KCDTYP
      CALL ABORTDB('CMOCTMAP','UNKNOWN CMA CODE TYPE',KCDTYP)
    ENDIF

!*          1.14 GROUND-BASED RADAR (ECMWF)
 
    ELSEIF(KOBTYP == NGBRAD) THEN
      KOTSQNO = NGBRADSQ

!*          1.14.1 BUFR GROUND-BASED RADAR RAIN RATES (ECMWF)

    IF(KCDTYP == NRADRR)  THEN
      KCDSQNO = NRADRRSQ

!*          1.14.9 UNKNOWN CMA CODE TYPE

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP'')')
      WRITE(KOUT,'('' UNKNOWN CMA CODE TYPE'')')
      WRITE(KOUT,'('' CMA OBS. TYPE:'',I10)') KOBTYP
      WRITE(KOUT,'('' CMA CODE TYPE:'',I10)') KCDTYP
      CALL ABORTDB('CMOCTMAP','UNKNOWN CMA CODE TYPE',KCDTYP)
    ENDIF

!*          1.14 RAIN GAUGES (ECMWF)
 
    ELSEIF(KOBTYP == NRAINGG) THEN
      KOTSQNO = NRAINGGSQ

!*          1.14.1 BUFR RAIN GAUGE DATA (ECMWF)

    IF(KCDTYP == NRADRR)  THEN
      KCDSQNO = NRADRRSQ

!*          1.14.9 UNKNOWN CMA CODE TYPE

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP'')')
      WRITE(KOUT,'('' UNKNOWN CMA CODE TYPE'')')
      WRITE(KOUT,'('' CMA OBS. TYPE:'',I10)') KOBTYP
      WRITE(KOUT,'('' CMA CODE TYPE:'',I10)') KCDTYP
      CALL ABORTDB('CMOCTMAP','UNKNOWN CMA CODE TYPE',KCDTYP)
    ENDIF

!*         1.15 LIDAR OBSERVATIONS

  ELSEIF(KOBTYP == NLIDAR) THEN 
    KOTSQNO = NLIDARSQ

!*          1.15.1 DOPPLER WIND LIDAR

    IF(KCDTYP == NDWLPCD)  THEN
      KCDSQNO = NDWLPCDSQ
!*          1.17   UNKNOWN CMA TYPE
    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP'')')
      WRITE(KOUT,'('' UNKNOWN CMA CODE TYPE'')')
      WRITE(KOUT,'('' CMA OBS. TYPE:'',I10)') KOBTYP
      WRITE(KOUT,'('' CMA CODE TYPE:'',I10)') KCDTYP
      CALL ABORTDB('CMOCTMAP','UNKNOWN CMA CODE TYPE',KCDTYP)
    ENDIF

!*         1.16 ALL-SKY SATELLITE RADIANCES
   ELSEIF(KOBTYP == NALLSKY) THEN 
      KOTSQNO = NALLSKYSQ

      IF(KCDTYP == NSSMI ) THEN
        KCDSQNO = NSSMISQ
      ELSE
        CALL ABORTDB('CMOCTMAP','UNKNOWN ALLSKY  CMA CODE TYPE',KCDTYP)
      ENDIF

!*         1.18 Interactive Multisensor Snow and Ice Mapping System 
   ELSEIF(KOBTYP == NIMSIMS) THEN
      KOTSQNO = NIMSIMSSQ

      IF(KCDTYP == NIMSIMS ) THEN
        KCDSQNO = NIMSIMSSQ
      ELSE
        CALL ABORTDB('CMOCTMAP','UNKNOWN IMS CMA CODE TYPE',KCDTYP)
      ENDIF

!*          1.17   UNKNOWN CMA TYPE

  ELSE
    WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP'')')
    WRITE(KOUT,'('' UNKNOWN CMA OBS. TYPE'')')
    WRITE(KOUT,'('' CMA OBS. TYPE:'',I10)') KOBTYP
    CALL ABORTDB('CMOCTMAP','UNKNOWN CMA OBS. TYPE',KOBTYP)
  ENDIF
!*
!-----------------------------------------------------------------------

!        5.       UNKNOWN MAPPING TYPE
!                 --------------------

ELSE
  WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP'')')
  WRITE(KOUT,'('' UNKNOWN MAPPING TYPE'')')
  WRITE(KOUT,'('' MAPPING TYPE:'',A)') CDMAP
  CALL ABORTDB('CMOCTMAP','UNKNOWN MAPPING TYPE',0)
ENDIF
!*
!-----------------------------------------------------------------------

!        6.       RETURN
!                 ------

IF (LHOOK) CALL DR_HOOK('CMOCTMAP',1,ZHOOK_HANDLE)
END SUBROUTINE CMOCTMAP
