SUBROUTINE CMOCTMAP_INV(CDMAP  ,KOUT   ,KOBTYP ,KCDTYP ,KOTSQNO,KCDSQNO )

!**** SUBROUTINE CMOCTMAP_INV - MAP CMA OBSERVATION AND CODE TYPES

!        D. VASILJEVIC    ECMWF    01/09/1994

!     PURPOSE
!     -------

!        MAP CMA OBSERVATION AND CODE TYPE INTO SEQUENCE NOS.

!**   INTERFACE
!     ---------

!        CALL CMOCTMAP_INV(CDMAP  ,KOUT   ,
!                      KOBTYP ,KCDTYP ,
!                      KOTSQNO,KCDSQNO )
!     WHERE:
!           CDMAP   = MAP EITHER CMA/BUFR INTO SEQUENCE NO. OR THE
!                     OTHER WAY ROUND
!           KOUT    = OUTPUT UNIT
!           KOBTYP  = OBS. TYPE
!           KCDTYP  = OBS. CODE TYPE
!           KOTSQNO = OBS. TYPE SEQUENCE NO.
!           KCDSQNO = OBS. CODE TYPE SEQUENCE NO.

!        CMOCTMAP_INV IS CALLED BY

!**   METHOD
!     ------

!        FOR EACH OBS. AND CODE TYPE WITHIN AN OBS. TYPE A SIMPLE
!     SEQUENCE NO. IS ASSIGNED.

!**   EXTERNALS
!     ---------

!        ENDRUN - ABORT

!**   MODIFICATIONS
!     -------------
!        Niels Bormann  23/12/2004  RARAD becomes LIMB; new codetypes for LIMB
!        Anne Fouilloux 31/03/2010 Add a new codetype for MERIS data (NTCWC)
!        Anne Fouilloux 29/07/2010 Add new codetype for GBRAD data
!        Patricia de Rosnay 16/05/2011 Add new land data (NADSCD)
!        M. Rennie      03/06/2011 Add obstype for LIDAR and move DWL
!        A. Geer        03-Jan-2012 New obstype for all-sky satellite radiances
!        P. Lopez       21-Aug-2012 New obstype for rain gauges
!        T. Kral        28-Jan-2014 New codetypes for TAMDAR, ACARS with mixing ratio,
!                       BUFR PILOT and BUFR SYNOP
!-----------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK

USE YOMCOCTP , ONLY : NSYNOP   ,NSYNOPSQ ,NSRSCD   ,NSRSCDSQ ,&
 & NATSCD   ,NATSCDSQ ,NADSCD   ,NADSCDSQ ,NSHSCD   ,NSHSCDSQ ,NABSCD   ,&
 & NABSCDSQ ,NSHRED   ,NSHREDSQ ,NATSHS   ,NATSHSSQ ,&
 & NAIREP   ,NAIREPSQ ,NAIRCD   ,NAIRCDSQ ,NCODAR   ,&
 & NCODARSQ ,NCOLBA   ,NCOLBASQ ,NAMDAR   ,NAMDARSQ ,&
 & NACARS   ,NACARSSQ ,NSIMAI   ,NSIMAISQ ,NSATOB   ,&
 & NSATOBSQ ,NSTBCD   ,NSTBCDSQ ,NSTB86   ,NSTB86SQ ,&
 & NSTB87   ,NSTB87SQ ,&
 & NSST     ,NSSTSQ   ,NDRIBU   ,NDRIBUSQ ,NDRBCD   ,&
 & NDRBCDSQ ,NBATHY   ,NBATHYSQ ,NTESAC   ,NTESACSQ ,&
 & NDERS1   ,NDERS1SQ ,NTEMP    ,NTEMPSQ  ,NLDTCD   ,&
 & NLDTCDSQ ,NSHTCD   ,NSHTCDSQ ,NTDROP   ,NTDROPSQ ,&
 & NROCOB   ,NROCOBSQ ,NROCSH   ,NROCSHSQ ,NMBTMP   ,&
 & NMBTMPSQ ,NSIMTE   ,NSIMTESQ ,NLBTEM   ,NLBTEMSQ ,&
 & NSBTEM   ,NSBTEMSQ ,NDBTEM   ,NDBTEMSQ ,NFBTEM   ,NFBTEMSQ ,&
 & NPILOT   ,NPILOTSQ ,&
 & NLDPCD   ,NLDPCDSQ ,NSHPCD   ,NSHPCDSQ ,NWPPCD   ,&
 & NWPPCDSQ ,&
 & NSATEM   ,NSATEMSQ ,NSTMCD   ,NSTMCDSQ ,&
 & NSTOVS   ,NSTOVSSQ ,NSTRESAT   ,NSTRESATSQ ,&
 & NSTDWL,&
 & NSTDWLSQ ,NSTTOV   ,NSTTOVSQ ,NGTSTB   ,NGTSTBSQ ,&
 & NGTST1   ,NGTST1SQ ,NGTST2   ,NGTST2SQ ,NGTHRB   ,&
 & NGTHRBSQ ,NGTHR1   ,NGTHR1SQ ,NGTHR2   ,NGTHR2SQ ,&
 & NSSMI    ,NSSMISQ  ,&
 & NPAOB    ,NPAOBSQ  ,NPABCD   ,NPABCDSQ ,NSCATT   ,&
 & NSCATTSQ ,NSCAT1   ,NSCAT1SQ ,NSCAT2   ,NSCAT2SQ ,&
 & NSCAT3   ,NSCAT3SQ ,NLIMB    ,NLIMBSQ  ,&
 & NSYRCD   ,NSYRCDSQ ,NSCAT4   ,NSCAT4SQ ,&
 & NSCAT5   ,NSCAT5SQ ,NSCAT6   ,NSCAT6SQ ,&
 & NSCAT7   ,NSCAT7SQ ,NSCAT8   ,NSCAT8SQ ,&
 & NEWPPCD  ,NEWPPCDSQ,NJWPPCD  ,NJWPPCDSQ          ,&
 & NRADOH   ,NRADOHSQ ,NTYPHO   ,NTYPHOSQ           ,&
 & NMETAR   ,NMETARSQ ,NPGPS    ,NPGPSSQ            ,&
 & NGPSRO   ,NGPSROSQ ,NLRAD    ,NLRADSQ            ,&
 & NRADAR   ,NRADARSQ ,NRADA1   ,NRADA1SQ           ,&
 & NSMOS    ,NSMOSSQ  ,&
 & NGBRAD   ,NGBRADSQ ,NRADRR   ,NRADRRSQ           ,&
 & NALLSKY  ,NALLSKYSQ, NIMSIMS, NIMSIMSSQ, NTCWC, NTCWCSQ, &
 & NISAC    ,NISACSQ  ,NISAC1   ,NISAC1SQ           ,&
 & NLIDAR   ,NLIDARSQ ,NDWLPCD  ,NDWLPCDSQ,&
 & NRAINGG  ,NRAINGGSQ,&
 & NTAMDAR  ,NTAMDARSQ,NACARSMR ,NACARSMRSQ,&
 & NMDEHS   ,NMDEHSSQ ,NAADSC   ,NAADSCSQ  ,&
 & NBLDPCD  ,NBLDPCDSQ,NBSHPCD  ,NBSHPCDSQ ,&
 & NBLSCD   ,NBLSCDSQ ,NBSSCD   ,NBSSCDSQ  ,&
 & NWAMDAR  ,NWAMDARSQ,NBUOYM   ,NBUOYMSQ  ,&
 & NBUOYD   ,NBUOYDSQ

IMPLICIT NONE

CHARACTER(LEN=*)  ,INTENT(IN)    :: CDMAP
INTEGER(KIND=JPIM),INTENT(IN)    :: KOUT
INTEGER(KIND=JPIM),INTENT(INOUT) :: KOBTYP
INTEGER(KIND=JPIM),INTENT(INOUT) :: KCDTYP
INTEGER(KIND=JPIM),INTENT(INOUT) :: KOTSQNO
INTEGER(KIND=JPIM),INTENT(INOUT) :: KCDSQNO
REAL(KIND=JPRB) :: ZHOOK_HANDLE

#include "abortdb.intfb.h"

!*
!-----------------------------------------------------------------------

!        1.        MAP CMA OBS. AND CODE TYPE INTO SEQUENCE NO.
!                  --------------------------------------------

IF (LHOOK) CALL DR_HOOK('CMOCTMAP_INV',0,ZHOOK_HANDLE)

IF(CDMAP == 'SQTOCODE' )     THEN

!*          3.1    SYNOP

  IF(KOTSQNO == NSYNOPSQ)           THEN
    KOBTYP  = NSYNOP

!*          3.1.1  SYNOP LAND REPORT

    IF(KCDSQNO == NSRSCDSQ)           THEN
      KCDTYP  = NSRSCD

!*          3.1.2  SYNOP LAND AUTOMATIC REPORT

    ELSEIF(KCDSQNO == NATSCDSQ)      THEN
      KCDTYP  = NATSCD

!*          3.1.3  SYNOP-SHIP REPORT

    ELSEIF(KCDSQNO == NSHSCDSQ)      THEN
      KCDTYP  = NSHSCD

!*          3.1.4  SYNOP-SHIP ABBREVIATED REPORT

    ELSEIF(KCDSQNO == NABSCDSQ)      THEN
      KCDTYP  = NABSCD

!*          3.1.5  SYNOP SHRED REPORT

    ELSEIF(KCDSQNO == NSHREDSQ)      THEN
      KCDTYP  = NSHRED

!*          3.1.6  SYNOP AUTOMATIC SHIP REPORT

    ELSEIF(KCDSQNO == NATSHSSQ)      THEN
      KCDTYP  = NATSHS

!*          3.1.7  FRENCH SYNOP AUTOMATIC LAND REPORT

    ELSEIF(KCDSQNO == NSYRCDSQ)      THEN
      KCDTYP  = NSYRCD

!*          3.1.8  FRENCH radome

    ELSEIF(KCDSQNO == NRADOHSQ)      THEN
      KCDTYP  = NRADOH

!*          3.1.9  METAR

    ELSEIF(KCDSQNO == NMETARSQ)      THEN
      KCDTYP  = NMETAR

!*          3.1.10 Ground-based GPS

    ELSEIF(KCDSQNO == NPGPSSQ)      THEN
      KCDTYP  = NPGPS

!*          3.1.11  ADDITIONAL LAND REPORT

    ELSEIF(KCDSQNO == NADSCDSQ)      THEN
      KCDTYP  = NADSCD

!*          3.1.12  BUFR LAND SYNOP REPORT

    ELSEIF(KCDSQNO == NBLSCDSQ)      THEN
      KCDTYP = NBLSCD

!*          3.1.13  BUFR Ship SYNOP REPORT

    ELSEIF(KCDSQNO == NBSSCDSQ)      THEN
      KCDTYP = NBSSCD

!*          3.1.14 UNKNOWN CMA CODE TYPE SEQUENCE NUMBER

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP_INV'')')
      WRITE(KOUT,'('' UNKNOWN SYNOP CMA CODE TYPE SEQUENCE NUMBER'')')
      WRITE(KOUT,'('' CMA CODE TYPE SEQ. NO.:'',I10)') KCDSQNO
      CALL ABORTDB('CMOCTMAP_INV','UNKNOWN SYNOP CMA CODE TYPE SEQUENCE NUMBER',KCDSQNO)
    ENDIF

!*          3.2    AIREP

  ELSEIF(KOTSQNO == NAIREPSQ)      THEN
    KOBTYP  = NAIREP

!*          3.2.1  AIRCRAFT REPORT

    IF(KCDSQNO == NAIRCDSQ)           THEN
      KCDTYP  = NAIRCD

!*          3.2.2  CODAR REPORT

    ELSEIF(KCDSQNO == NCODARSQ)       THEN
      KCDTYP  = NCODAR

!*          3.2.3  COLBA REPORT

    ELSEIF(KCDSQNO == NCOLBASQ)       THEN
      KCDTYP  = NCOLBA

!*          3.2.4  AMDAR AIRCRAFT REPORT

    ELSEIF(KCDSQNO == NAMDARSQ)       THEN
      KCDTYP  = NAMDAR

!*          3.2.5  ACARS AIRCRAFT REPORT

    ELSEIF(KCDSQNO == NACARSSQ)       THEN
      KCDTYP  = NACARS

!*          3.2.6  SIMULATED AIREP REPORT

    ELSEIF(KCDSQNO == NSIMAISQ)       THEN
      KCDTYP  = NSIMAI

!*          3.2.7  TAMDAR AIRCRAFT REPORT

    ELSEIF(KCDSQNO == NTAMDARSQ)      THEN
      KCDTYP = NTAMDAR

!*          3.2.8  ACARS WITH MIXING RATIO

    ELSEIF(KCDSQNO == NACARSMRSQ)     THEN
      KCDTYP = NACARSMR

!*          3.2.9  WIGOS AMDAR AIRCRAFT REPORT

    ELSEIF(KCDSQNO == NWAMDARSQ)       THEN
      KCDTYP  = NWAMDAR

!*          3.2.10  MODE-S EHS AIRCRAFT REPORT

    ELSEIF(KCDSQNO == NMDEHSSQ)       THEN
      KCDTYP  = NMDEHS

!*          3.2.11  ADS-C AIRCRAFT REPORT

    ELSEIF(KCDSQNO == NAADSCSQ)       THEN
      KCDTYP  = NAADSC

!*          3.2.12 UNKNOWN CMA CODE TYPE SEQUENCE NUMBER

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP_INV'')')
      WRITE(KOUT,'('' UNKNOWN AIRCRAFT CMA CODE TYPE SEQUENCE NUMBER'')')
      WRITE(KOUT,'('' CMA CODE TYPE SEQ. NO.:'',I10)') KCDSQNO
      CALL ABORTDB('CMOCTMAP_INV','UNKNOWN AIRCRAFT CMA CODE TYPE SEQUENCE NUMBER',KCDSQNO)
    ENDIF

!*          3.3    SATOB

  ELSEIF(KOTSQNO == NSATOBSQ)       THEN
    KOBTYP  = NSATOB

!*          3.3.1  SATOB REPORT

    IF(KCDSQNO == NSTBCDSQ)            THEN
      KCDTYP  = NSTBCD

!*          3.3.2  HIGH RES. VIS WIND SATOB REPORT

    ELSEIF(KCDSQNO == NSTB86SQ)            THEN
      KCDTYP  = NSTB86

!*          3.3.3  SST REPORT

    ELSEIF(KCDSQNO == NSSTSQ  )       THEN
      KCDTYP  = NSST

!*          3.3.4  AMV SATOB REPORT

    ELSEIF(KCDSQNO == NSTB87SQ)            THEN
      KCDTYP  = NSTB87

!*          3.3.9  UNKNOWN CMA CODE TYPE SEQUENCE NUMBER

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP_INV'')')
      WRITE(KOUT,'('' UNKNOWN SATOB CMA CODE TYPE SEQUENCE NUMBER'')')
      WRITE(KOUT,'('' CMA CODE TYPE SEQ. NO.:'',I10)') KCDSQNO
      CALL ABORTDB('CMOCTMAP_INV','UNKNOWN SATOB CMA CODE TYPE SEQUENCE NUMBER',KCDSQNO)
    ENDIF

!*          3.4    DRIBU

  ELSEIF(KOTSQNO == NDRIBUSQ)       THEN
    KOBTYP  = NDRIBU

!*          3.4.1  DRIBU REPORT

    IF(KCDSQNO == NDRBCDSQ)            THEN
      KCDTYP  = NDRBCD

!*          3.4.2  BATHY REPORT

    ELSEIF(KCDSQNO == NBATHYSQ)       THEN
      KCDTYP  = NBATHY

!*          3.4.3  TESAC REPORT

    ELSEIF(KCDSQNO == NTESACSQ)       THEN
      KCDTYP  = NTESAC

!*          3.4.4  ERS1 AS DRIBU

    ELSEIF(KCDSQNO == NDERS1SQ)       THEN
      KCDTYP  = NDERS1

!*          3.4.5  ERS1 AS DRIBU

    ELSEIF(KCDSQNO == NBUOYMSQ)       THEN
      KCDTYP  = NBUOYM

!*          3.4.6  ERS1 AS DRIBU

    ELSEIF(KCDSQNO == NBUOYDSQ)       THEN
      KCDTYP  = NBUOYD

!*          3.4.9  UNKNOWN CMA CODE TYPE SEQUENCE NUMBER

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP_INV'')')
      WRITE(KOUT,'('' UNKNOWN DRIBU CMA CODE TYPE SEQUENCE NUMBER'')')
      WRITE(KOUT,'('' CMA CODE TYPE SEQ. NO.:'',I10)') KCDSQNO
      CALL ABORTDB('CMOCTMAP_INV','UNKNOWN DRIBU CMA CODE TYPE SEQUENCE NUMBER',KCDSQNO)
    ENDIF

!*          3.5    TEMP

  ELSEIF(KOTSQNO == NTEMPSQ )       THEN
    KOBTYP  = NTEMP

!*          3.5.1  LAND TEMP REPORT

    IF(KCDSQNO == NLDTCDSQ)            THEN
      KCDTYP  = NLDTCD

!*          3.5.2  TEMP SHIP REPORT

    ELSEIF(KCDSQNO == NSHTCDSQ)       THEN
      KCDTYP  = NSHTCD

!*          3.5.3  TEMP-DROP REPORT

    ELSEIF(KCDSQNO == NTDROPSQ)       THEN
      KCDTYP  = NTDROP

!*          3.5.4  ROCOB REPORT

    ELSEIF(KCDSQNO == NROCOBSQ)       THEN
      KCDTYP  = NROCOB

!*          3.5.5  ROCOB SHIP REPORT

    ELSEIF(KCDSQNO == NROCSHSQ)       THEN
      KCDTYP  = NROCSH

!*          3.5.6  MOBILE TEMP REPORT

    ELSEIF(KCDSQNO == NMBTMPSQ)       THEN
      KCDTYP  = NMBTMP

!*          3.5.7  SIMULATED TEMP STATION CODE TYPE

    ELSEIF(KCDSQNO == NSIMTESQ)       THEN
      KCDTYP  = NSIMTE

!*          3.5.8  BUFR Land TEMP

    ELSEIF(KCDSQNO == NLBTEMSQ)       THEN
      KCDTYP  = NLBTEM

!*          3.5.9  BUFR Ship TEMP

    ELSEIF(KCDSQNO == NSBTEMSQ)       THEN
      KCDTYP  = NSBTEM

!*          3.5.10 BUFR TEMP DROP

    ELSEIF(KCDSQNO == NDBTEMSQ)       THEN
      KCDTYP  = NDBTEM

!*          3.5.11 BUFR TEMP DESCENT

    ELSEIF(KCDSQNO == NFBTEMSQ)       THEN
      KCDTYP  = NFBTEM

!*          3.5.12 UNKNOWN CMA CODE TYPE SEQUENCE NUMBER

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP_INV'')')
      WRITE(KOUT,'('' UNKNOWN TEMP CMA CODE TYPE SEQUENCE NUMBER'')')
      WRITE(KOUT,'('' CMA CODE TYPE SEQ. NO.:'',I10)') KCDSQNO
      CALL ABORTDB('CMOCTMAP_INV','UNKNOWN TEMP CMA CODE TYPE SEQUENCE NUMBER',KCDSQNO)
    ENDIF

!*          3.6    PILOT

  ELSEIF(KOTSQNO == NPILOTSQ)       THEN
    KOBTYP  = NPILOT

!*          3.6.1  LAND PILOT REPORT

    IF(KCDSQNO == NLDPCDSQ)            THEN
      KCDTYP  = NLDPCD

!*          3.6.2  SHIP PILOT REPORT

    ELSEIF(KCDSQNO == NSHPCDSQ)       THEN
      KCDTYP  = NSHPCD

!*          3.6.3  AMERICAN WIND PROFILERS

    ELSEIF(KCDSQNO == NWPPCDSQ)       THEN
      KCDTYP  = NWPPCD

!*          3.6.4  EUROPEAN WIND PROFILERS

    ELSEIF(KCDSQNO == NEWPPCDSQ)       THEN
      KCDTYP  = NEWPPCD

!*          3.6.5  JAPANESE WIND PROFILERS

    ELSEIF(KCDSQNO == NJWPPCDSQ)       THEN
      KCDTYP  = NJWPPCD

!*          3.6.6  BUFR LAND PILOT REPORT

    ELSEIF(KCDSQNO == NBLDPCDSQ)       THEN
      KCDTYP = NBLDPCD

!*          3.6.7  BUFR SHIP PILOT REPORT

    ELSEIF(KCDSQNO == NBSHPCDSQ)       THEN
      KCDTYP = NBSHPCD

!*          3.6.6a  MOBILE WIND PILOT - OBSOLETE


!*          3.6.9  UNKNOWN CMA CODE TYPE SEQUENCE NUMBER

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP_INV'')')
      WRITE(KOUT,'('' UNKNOWN PILOT CMA CODE TYPE SEQUENCE NUMBER'')')
      WRITE(KOUT,'('' CMA CODE TYPE SEQ. NO.:'',I10)') KCDSQNO
      CALL ABORTDB('CMOCTMAP_INV','UNKNOWN PILOT CMA CODE TYPE SEQUENCE NUMBER',KCDSQNO)
    ENDIF

!*          3.7    SATEM

  ELSEIF(KOTSQNO == NSATEMSQ)       THEN
    KOBTYP  = NSATEM

!*          3.7.1  SATEM REPORT

    IF(KCDSQNO == NSTMCDSQ)            THEN
      KCDTYP  = NSTMCD

!*          3.7.2  HIGH RESOLUTION SATTELITE REPORT

    ELSEIF(KCDSQNO == NSTOVSSQ)       THEN
      KCDTYP  = NSTOVS

!*          3.7.3  HIGH RESOLUTION SIMULATED DWL SATELLITE REPORT

    ELSEIF(KCDSQNO == NSTDWLSQ)       THEN
      KCDTYP  = NSTDWL

!*          3.7.4  HIGH RESOLUTION SIMULATED TOVS SATELLITE REPORT

    ELSEIF(KCDSQNO == NSTTOVSQ)       THEN
      KCDTYP  = NSTTOV

!*          3.7.5  GTS BUFR SATEM REPORT
!                  (250 KM TEMP AND HUM PROFILES)

    ELSEIF(KCDSQNO == NGTSTBSQ)       THEN
      KCDTYP  = NGTSTB

!*          3.7.6  GTS BUFR SATEM CLEAR RADIANCE REPORT

    ELSEIF(KCDSQNO == NGTST1SQ)       THEN
      KCDTYP  = NGTST1

!*          3.7.7  GTS BUFR SATEM RETR PROFILES AND
!                  CLEAR RADIANCES REPORT

    ELSEIF(KCDSQNO == NGTST2SQ)       THEN
      KCDTYP  = NGTST2

!*          3.7.8  HIGH RES 80 KM BUFR NON GTS SATEM RETR PROFILES

    ELSEIF(KCDSQNO == NGTHRBSQ)       THEN
      KCDTYP  = NGTHRB

!*          3.7.9  HIGH RES 80 KM BUFR NON GTS SATEM CLEAR
!                  RADIANCE REPORT

    ELSEIF(KCDSQNO == NGTHR1SQ)       THEN
      KCDTYP  = NGTHR1

!*          3.7.10 HIGH RES 80 KM BUFR NON GTS SATEM PROFILES AND
!                  CLEAR RADIANCE REPORT

    ELSEIF(KCDSQNO == NGTHR2SQ)       THEN
      KCDTYP  = NGTHR2

!*          3.7.11 RETRIEVED OZONE LAYERS REPORT
!BEN- NOW INCLUDING ALSO RETRIEVED AEROSOL OPTICAL DEPTH!!!!!

    ELSEIF(KCDSQNO == NSTRESATSQ )       THEN
      KCDTYP  = NSTRESAT

!*          3.7.12 SMOS REPORT

    ELSEIF(KCDSQNO == NSMOSSQ )       THEN
      KCDTYP  = NSMOS

!*          3.7.13 MERIS

    ELSEIF(KCDSQNO == NTCWCSQ )       THEN
      KCDTYP  = NTCWC

!*          3.7.14 UNKNOWN CMA CODE TYPE SEQUENCE NUMBER

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP_INV'')')
      WRITE(KOUT,'('' UNKNOWN SATEM CMA CODE TYPE SEQUENCE NUMBER'')')
      WRITE(KOUT,'('' CMA CODE TYPE SEQ. NO.:'',I10)') KCDSQNO
      CALL ABORTDB('CMOCTMAP_INV','UNKNOWN SATEM CMA CODE TYPE SEQUENCE NUMBER',KCDSQNO)
    ENDIF

!*          3.8    PAOB

  ELSEIF(KOTSQNO == NPAOBSQ )       THEN
    KOBTYP  = NPAOB

!*          3.8.1  PAOB REPORT

    IF(KCDSQNO == NPABCDSQ)            THEN
      KCDTYP  = NPABCD

!*          3.8.2  donnees cyclone

    ELSEIF(KCDSQNO == NTYPHOSQ)            THEN
      KCDTYP  = NTYPHO

!*          3.8.9  UNKNOWN CMA CODE TYPE SEQUENCE NUMBER

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP_INV'')')
      WRITE(KOUT,'('' UNKNOWN PAOB CMA CODE TYPE SEQUENCE NUMBER'')')
      WRITE(KOUT,'('' CMA CODE TYPE SEQ. NO.:'',I10)') KCDSQNO
      CALL ABORTDB('CMOCTMAP_INV','UNKNOWN PAOB CMA CODE TYPE SEQUENCE NUMBER',KCDSQNO)
    ENDIF

!*          3.9    SCATTEROMETER

  ELSEIF(KOTSQNO == NSCATTSQ)       THEN
    KOBTYP  = NSCATT

!*          3.9.1  SCATT. CODE TYPE 1

    IF(KCDSQNO == NSCAT1SQ)            THEN
      KCDTYP  = NSCAT1

!*          3.9.2  SCATT. CODE TYPE 2

    ELSEIF(KCDSQNO == NSCAT2SQ)            THEN
      KCDTYP  = NSCAT2

!*          3.9.3  SCATT. CODE TYPE 3

    ELSEIF(KCDSQNO == NSCAT3SQ)            THEN
      KCDTYP  = NSCAT3

!*          3.9.4  SCATT. CODE TYPE 4

    ELSEIF(KCDSQNO == NSCAT4SQ)            THEN
      KCDTYP  = NSCAT4

!*          3.9.5  SCATT. CODE TYPE 5

    ELSEIF(KCDSQNO == NSCAT5SQ)            THEN
      KCDTYP  = NSCAT5

!*          3.9.6  SCATT. CODE TYPE 6

    ELSEIF(KCDSQNO == NSCAT6SQ)            THEN
      KCDTYP  = NSCAT6

!*          3.9.7  SCATT. CODE TYPE 7

    ELSEIF(KCDSQNO == NSCAT7SQ)            THEN
      KCDTYP  = NSCAT7

!*          3.9.8  SCATT. CODE TYPE 8

    ELSEIF(KCDSQNO == NSCAT8SQ)            THEN
      KCDTYP  = NSCAT8

!*          3.9.7  UNKNOWN CMA CODE TYPE SEQUENCE NUMBER

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP_INV'')')
      WRITE(KOUT,'('' UNKNOWN SCATT. CMA CODE TYPE SEQUENCE NUMBER'')')
      WRITE(KOUT,'('' CMA CODE TYPE SEQ. NO.:'',I10)') KCDSQNO
      CALL ABORTDB('CMOCTMAP_INV','UNKNOWN SCATT. CMA CODE TYPE SEQUENCE NUMBER',KCDSQNO)
    ENDIF

!*          3.10   LIMB OBSERVATIONS

  ELSEIF(KOTSQNO == NLIMBSQ)       THEN
    KOBTYP  = NLIMB

!*          3.10.1 GPS RO

    IF(KCDSQNO == NGPSROSQ)            THEN
      KCDTYP = NGPSRO

!*          3.10.2 Limb radiances

    ELSEIF(KCDSQNO == NLRADSQ)            THEN
      KCDTYP = NLRAD

!*          3.10.9 UNKNOWN CMA CODE TYPE SEQUENCE NUMBER

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP_INV'')')
      WRITE(KOUT,'('' UNKNOWN LIMB CMA CODE TYPE SEQUENCE NUMBER'')')
      WRITE(KOUT,'('' CMA CODE TYPE SEQ. NO.:'',I10)') KCDSQNO
      CALL ABORTDB('CMOCTMAP_INV','UNKNOWN LIMB CMA CODE TYPE SEQUENCE NUMBER',KCDSQNO)
    ENDIF

!*          3.11 In-situ atmospheric composition (ISAC)

    ELSEIF(KOTSQNO == NISACSQ) THEN
      KOBTYP  = NISAC

!*          3.11.1 IAGOS aircraft data

      IF(KCDSQNO == NISAC1SQ)            THEN
        KCDTYP  = NISAC1

!*          3.11.9 UNKNOWN CMA CODE TYPE SEQUENCE NUMBER

      ELSE
        WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP'')')
        WRITE(KOUT,'('' UNKNOWN ISAC CMA CODE TYPE'',&
          &'' SEQUENCE NUMBER'')')
        WRITE(KOUT,'('' CMA CODE TYPE SEQ. NO.:'',I10)') KCDSQNO
        CALL ABORTDB('CMOCTMAP','UNKNOWN ISAC CMA CODE TYPE SEQUENCE NUMBER',&
         & KCDSQNO)
      ENDIF

!*              3.12

  ELSEIF(KOTSQNO == 12) THEN
    KOBTYP  = 12

!*          3.13  RADAR
  ELSEIF(KOTSQNO == NRADARSQ)   THEN
    KOBTYP  = NRADAR


!*          3.13.1 BUFR RADAR REFLECTIVITY 1

     IF(KCDSQNO == NRADA1SQ)            THEN
       KCDTYP  = NRADA1

!*          3.13.9 UNKNOWN CMA CODE TYPE SEQUENCE NUMBER

     ELSE
       WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP_INV'')')
       WRITE(KOUT,'('' UNKNOWN RADAR CMA CODE TYPE'',&
         &'' SEQUENCE NUMBER'')')
       WRITE(KOUT,'('' CMA CODE TYPE SEQ. NO.:'',I10)') KCDSQNO
       CALL ABORTDB('CMOCTMAP_INV','UNKNOWN RADAR CMA CODE TYPE SEQUENCE NUMBER',&
        & KCDSQNO)
     ENDIF

!*          3.14 GROUND-BASED RADAR (ECMWF)

    ELSEIF(KOTSQNO == NGBRADSQ) THEN
      KOBTYP  = NGBRAD

!*          3.14.1 BUFR GROUND-BASED RADAR RAIN RATES (ECMWF)

      IF(KCDSQNO == NRADRRSQ)            THEN
        KCDTYP  = NRADRR

!*          3.14.9 UNKNOWN CMA CODE TYPE SEQUENCE NUMBER

      ELSE
        WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP'')')
        WRITE(KOUT,'('' UNKNOWN ECMWF GROUND-BASED RADAR CMA CODE TYPE'',&
          &'' SEQUENCE NUMBER'')')
        WRITE(KOUT,'('' CMA CODE TYPE SEQ. NO.:'',I10)') KCDSQNO
        CALL ABORTDB('CMOCTMAP','UNKNOWN ECMWF GROUND-BASED RADAR CMA CODE TYPE SEQUENCE NUMBER',&
         & KCDSQNO)
      ENDIF


!*          3.14 RAIN GAUGES (ECMWF)

    ELSEIF(KOTSQNO == NRAINGGSQ) THEN
      KOBTYP  = NRAINGG

!*          3.14.1 BUFR RAIN GAUGE DATA (ECMWF)

      IF(KCDSQNO == NRADRRSQ) THEN
        KCDTYP  = NRADRR

!*          3.14.9 UNKNOWN CMA CODE TYPE SEQUENCE NUMBER

      ELSE
        WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP'')')
        WRITE(KOUT,'('' UNKNOWN ECMWF GROUND-BASED RADAR CMA CODE TYPE'',&
          &'' SEQUENCE NUMBER'')')
        WRITE(KOUT,'('' CMA CODE TYPE SEQ. NO.:'',I10)') KCDSQNO
        CALL ABORTDB('CMOCTMAP','UNKNOWN ECMWF GROUND-BASED RADAR CMA CODE TYPE SEQUENCE NUMBER',&
         & KCDSQNO)
      ENDIF


!*           3.15 LIDAR observations

  ELSEIF(KOTSQNO == NLIDARSQ) THEN
    KOBTYP = NLIDAR

!*          3.15.1 DOPPLER WIND LIDAR

    IF(KCDSQNO == NDWLPCDSQ)       THEN
      KCDTYP  = NDWLPCD

!*          3.15.9 UNKNOWN CMA CODE TYPE SEQUENCE NUMBER

    ELSE
      WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP'')')
      WRITE(KOUT,'('' UNKNOWN ECMWF GROUND-BASED RADAR CMA CODE TYPE'',&
        &'' SEQUENCE NUMBER'')')
      WRITE(KOUT,'('' CMA CODE TYPE SEQ. NO.:'',I10)') KCDSQNO
      CALL ABORTDB('CMOCTMAP','UNKNOWN ECMWF GROUND-BASED RADAR CMA CODE TYPE SEQUENCE NUMBER',&
      & KCDSQNO)
    ENDIF

!*          3.14159 ALL-SKY

  ELSEIF(KOTSQNO == NALLSKYSQ) THEN
    KOBTYP  = NALLSKY

    IF(KCDSQNO == NSSMISQ )       THEN
      KCDTYP  = NSSMI
    ELSE
      CALL ABORTDB('CMOCTMAP_INV','UNKNOWN ALLSKY CMA CODE TYPE SEQUENCE NUMBER',KCDSQNO)
    ENDIF

!*             Interactive Multisensor Snow and Ice Mapping System

  ELSEIF(KOTSQNO == NIMSIMSSQ) THEN
    KOBTYP  = NIMSIMS

    IF(KCDSQNO == 1 )       THEN
      KCDTYP  = NIMSIMS
    ELSE
      CALL ABORTDB('CMOCTMAP_INV','UNKNOWN IMS CMA CODE TYPE SEQUENCE NUMBER',KCDSQNO)
    ENDIF



!*          3.15   UNKNOWN CMA OBS. TYPE SEQUENCE NO.

  ELSE
    WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP_INV'')')
    WRITE(KOUT,'('' UNKNOWN CMA OBS. TYPE SEQUENCE NUMBER'')')
    WRITE(KOUT,'('' CMA OBS. TYPE SEQ. NO.:'',I10)') KOTSQNO
!*AF    CALL ABORTDB('CMOCTMAP_INV','UNKNOWN CMA OBS. TYPE SEQUENCE NUMBER',KOTSQNO)
  ENDIF
!*
!-----------------------------------------------------------------------

!        5.       UNKNOWN MAPPING TYPE
!                 --------------------

ELSE
  WRITE(KOUT,'(''0ERROR IN SUBROUTINE CMOCTMAP_INV'')')
  WRITE(KOUT,'('' UNKNOWN MAPPING TYPE'')')
  WRITE(KOUT,'('' MAPPING TYPE:'',A)') CDMAP
  CALL ABORTDB('CMOCTMAP_INV','UNKNOWN MAPPING TYPE',0)
ENDIF
!*
!-----------------------------------------------------------------------

!        6.       RETURN
!                 ------

IF (LHOOK) CALL DR_HOOK('CMOCTMAP_INV',1,ZHOOK_HANDLE)
END SUBROUTINE CMOCTMAP_INV
