#!/bin/csh
#
# DART software - Copyright UCAR. This open source software is provided
# provided by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download
#
# ------------------------------------------------------------------------------
# Purpose: perform a multi-instance advance of CLM and then assimilate.
#          The assumptions here are that there is an ensemble of CLM states
#          available (as well as the CESM-required ROF states).
#
# The example configured here is for daily assimilation - at 00Z.
# Some variables for the DART state come from the CLM restart file,
# some from the .h0. file that has 30-minute values in it, some from
# a .h2. file that is still in the vector-based format.
#
# An example of assimilating monthly can be found in CLM5_monthly_assim.csh
# ------------------------------------------------------------------------------

# All the user-specified variables and settings are read from a DART
# parameter file. This includes the case name, ensemble size, the location
# of the CESM code, etc. There are still some variables that are logically
# defined in this script, as well as some specifics about the CLM namelists.

source DART_params_d4o_template_GSWP.csh

# Prevent accidental removal of an experiment.
# If you want to replace the experiment, you have to manually
# remove the directories. 

if ( -e ${caseroot} ) then
   echo "WARNING : ${caseroot} already exists."
   echo "EXISTING: ${caseroot}"
   echo "EXISTING: ${exeroot}"
   echo "EXISTING: ${rundir}"
   echo "These directories need to be removed or the case must be renamed"
   echo "WARNING : Stopping."
   exit
endif

# ==============================================================================
# job settings:
#
# run_queue, run_time, st_archive_queue, st_archive_time may be changed at any time
#LGG should changed into /work/cmcc/gc02720/spreads-cmcc-cm/ccs_config/machines/config_batch.xml
#inside zeus section the queue from p_short into p_dev
setenv run_queue regular
setenv run_time 01:30:00

# the short-term archiver is turned off (initially?) to let you explore the
# run directory

setenv short_term_archiver off
setenv st_archive_queue share
setenv st_archive_time 01:00:00

# ==============================================================================
# Create the case - this creates the CASEROOT directory.
#
# FATAL idea to make caseroot the same dir as where this setup script is
# since the build process removes all files in the caseroot dir before
# populating it.  try to prevent shooting yourself in the foot.

if ( ${caseroot} == `pwd` ) then
   echo "ERROR: the setup script should not be located in the caseroot"
   echo "directory, because all files in the caseroot dir will be removed"
   echo "before creating the new case.  move the script to a safer place."
   exit 1
endif

echo "removing old files from ${caseroot}"
echo "removing old files from ${exeroot}"
echo "removing old files from ${rundir}"

${REMOVE} ${caseroot}
${REMOVE} ${exeroot}
${REMOVE} ${rundir}
echo "${cesmroot}/cime/scripts/create_newcase  --res  ${resolution} \
                                         --mach ${mach} \
                                         --compset ${compset} \
                                         --case ${caseroot} \
                                         --project ${project} \
                                         --run-unsupported \
                                         --ninst ${num_instances} \
                                         --driver mct || exit 2"
${cesmroot}/cime/scripts/create_newcase  --res  ${resolution} \
                                         --mach ${mach} \
                                         --compset ${compset} \
                                         --case ${caseroot} \
                                         --project ${project} \
                                         --run-unsupported \
#                                         --driver mct \
                                         --ninst ${num_instances} || exit 2

# ==============================================================================
# Preserve a copy of this script and the parameter file as it was run.
# Copy the DART setup script (CESM_DART_config) to CASEROOT.

set ThisFileName = $0:t
${COPY} $ThisFileName       ${caseroot}/${ThisFileName}.original
${COPY} DART_params_d4o_template_GSWP.csh     ${caseroot}/DART_params.csh
${COPY} CESM_DART_config    ${caseroot}

#${COPY} run_filter.bash ${caseroot}/run/.

# ==============================================================================
cd ${caseroot}
# ==============================================================================

# Save a copy for debug purposes
foreach FILE ( *xml )
   if ( ! -e          ${FILE}.original ) then
      ${COPY} ${FILE} ${FILE}.original
   endif
end

# Get a bunch of environment variables.
# If any of these are changed by xmlchange calls in this program,
# then they must be explicty changed with setenv calls too.

setenv COMPSET               `./xmlquery COMPSET               --value` || exit 3
setenv COMP_ATM              `./xmlquery COMP_ATM              --value` || exit 3
setenv COMP_OCN              `./xmlquery COMP_OCN              --value` || exit 3
setenv CASEROOT              `./xmlquery CASEROOT              --value` || exit 3

# Make sure the case is configured with a stub ocean and a data atmosphere.

if ( (${COMP_OCN} != socn) || (${COMP_ATM} != datm) ) then
   echo " "
   echo "ERROR: This script is not appropriate for active ocean or atmospheric compsets."
   echo " "
   exit 3
endif

./xmlchange STOP_OPTION=${stop_option}
./xmlchange STOP_N=${stop_n}
./xmlchange RESUBMIT=${resubmit}

./xmlchange CALENDAR=NO_LEAP
./xmlchange CIME_OUTPUT_ROOT=${cime_output_root}
./xmlchange EXEROOT=${exeroot}
./xmlchange RUNDIR=${rundir}

# This comes from http://esmci.github.io/cime/data_models/data-atm.html
# "Note If DATM_MODE is set to CPLHIST, it is normally assumed that the model
# domain will be identical to all of the stream domains. To ensure this, the
# xml variables ATM_DOMAIN_PATH and ATM_DOMAIN_FILE are ignored and a valid
# setting must be given for DATM_CPLHIST_DOMAIN_FILE. If DATM_CPLHIST_DOMAIN_FILE
# is set to null, then the datm component domain information is read in from
# the first coupler history file in the target stream and it is assumed that the
# first coupler stream file that is pointed to contains the domain information
# for that stream. This is the default that should be used for this mode."

#./xmlchange DATM_MODE=CLMCRUNCEPv7
./xmlchange DATM_MODE=CLMGSWP3v1
./xmlchange DATM_CPLHIST_DOMAIN_FILE=null
#./xmlchange DATM_CLMNCEP_YR_ALIGN=${stream_year_align}
#./xmlchange DATM_CLMNCEP_YR_START=${stream_year_first}
#./xmlchange DATM_CLMNCEP_YR_END=${stream_year_last}

./xmlchange DATM_YR_ALIGN=${stream_year_align}
./xmlchange DATM_YR_START=${stream_year_first}
./xmlchange DATM_YR_END=${stream_year_last}


# --- In a hybrid run the model is initialized as a startup, BUT uses
# initialization datasets FROM A PREVIOUS case.  This
# is somewhat analogous to a branch run with relaxed restart
# constraints.  A hybrid run allows users to bring together combinations
# of initial/restart files from a previous case (specified by
# RUN_REFCASE) at a given model output date (specified by
# RUN_REFDATE). Unlike a branch run, the starting date of a hybrid run
# (specified by RUN_STARTDATE) can be modified relative to the reference
# case. In a hybrid run, the model does not continue in a bit-for-bit
# fashion with respect to the reference case. The resulting climate,
# however, should be continuous provided that no model source code or
# namelists are changed in the hybrid run.  In a hybrid initialization,
# the ocean model does not start until the second ocean coupling
# (normally the second day), and the coupler does a cold start without
# a restart file.</desc>

./xmlchange RUN_TYPE=hybrid
./xmlchange RUN_REFCASE=${refcase}
./xmlchange RUN_REFDATE=${refdate}
./xmlchange RUN_REFTOD=${reftod}
./xmlchange GET_REFCASE=FALSE

./xmlchange RUN_STARTDATE=${startdate}
./xmlchange START_TOD=${start_tod}

# pnetcdf is default
./xmlchange PIO_TYPENAME=pnetcdf
./xmlchange PIO_STRIDE=18

# Task layout:
# Set the nodes_per_instance below to match your case.
# By computing task counts like we do below, we guarantee each instance uses
# a whole number of nodes which is the recommended configuration.
# CIME interprets a negative task count as representing the number of nodes.
# On Cheyenne (at least) using multiple threads is not recommended.

@ nthreads = ${number_of_threads}

@ atm_tasks = -1 * ${nodes_per_instance}
@ cpl_tasks = -1 * ${nodes_per_instance}
@ ocn_tasks = -1 * ${nodes_per_instance}
@ wav_tasks = -1 * ${nodes_per_instance}
@ glc_tasks = -1 * ${nodes_per_instance}
@ ice_tasks = -1 * ${nodes_per_instance}
@ rof_tasks = -1 * ${nodes_per_instance}
@ lnd_tasks = -1 * ${nodes_per_instance}
@ esp_tasks = -1 * ${nodes_per_instance}

./xmlchange ROOTPE_ATM=0,NTHRDS_ATM=$nthreads,NTASKS_ATM=$atm_tasks
./xmlchange ROOTPE_CPL=0,NTHRDS_CPL=$nthreads,NTASKS_CPL=$cpl_tasks
./xmlchange ROOTPE_OCN=0,NTHRDS_OCN=$nthreads,NTASKS_OCN=$ocn_tasks
./xmlchange ROOTPE_WAV=0,NTHRDS_WAV=$nthreads,NTASKS_WAV=$wav_tasks
./xmlchange ROOTPE_GLC=0,NTHRDS_GLC=$nthreads,NTASKS_GLC=$glc_tasks
./xmlchange ROOTPE_ICE=0,NTHRDS_ICE=$nthreads,NTASKS_ICE=$ice_tasks
./xmlchange ROOTPE_ROF=0,NTHRDS_ROF=$nthreads,NTASKS_ROF=$rof_tasks
./xmlchange ROOTPE_LND=0,NTHRDS_LND=$nthreads,NTASKS_LND=$lnd_tasks
./xmlchange ROOTPE_ESP=0,NTHRDS_ESP=$nthreads,NTASKS_ESP=$esp_tasks

./xmlchange --subgroup case.run --id JOB_QUEUE          --val ${run_queue}
./xmlchange --subgroup case.run --id JOB_WALLCLOCK_TIME --val ${run_time}


#./xmlchange NTASKS=72
#./xmlchange NTASKS_LND=72

#AV27223 NTASKS = tasks number per member (min = 1 ; max = number of cores per node)
#AV27223 More tasks can be related with more performance

# JUNO
# ./xmlchange NTASKS=36
# ./xmlchange NTASKS_LND=36

# Cassandra - To test .. tested model with 36 
./xmlchange NTASKS=56
./xmlchange NTASKS_LND=56

#./xmlchange DATM_CPLHIST_DIR=/work/cmcc/lg07622/land/forcing

echo "setting up the case ... "

./case.setup || exit 4

echo "case setup finished."

# ==============================================================================
# These are archiving options that may be used.

if (${short_term_archiver} == 'off') then
   ./xmlchange DOUT_S=FALSE
else
   ./xmlchange DOUT_S=TRUE
   ./xmlchange --subgroup case.st_archive --id JOB_QUEUE          --val ${st_archive_queue}
   ./xmlchange --subgroup case.st_archive --id JOB_WALLCLOCK_TIME --val ${st_archive_time}
endif

# DEBUG = TRUE implies turning on run and compile time debugging.
# INFO_DBUG level of debug output, 0=minimum, 1=normal, 2=more, 3=too much.

./xmlchange DEBUG=FALSE
./xmlchange INFO_DBUG=0

# ==============================================================================
# Use the stream template that has all CAM reanalysis years available.

   # set STREAMFILE_SOLAR        = datm.streams.txt.CLMCRUNCEPv7.Solar
   # set STREAMFILE_PRECI        = datm.streams.txt.CLMCRUNCEPv7.Precip
   # set STREAMFILE_TPQW         = datm.streams.txt.CLMCRUNCEPv7.TPQW


# ==============================================================================
# Modify namelist templates for each instance.
#
# In a hybrid run with CONTINUE_RUN = FALSE (i.e. just starting up):
# CLM builds its own 'finidat' value from the REFCASE variables.
#
# All of these must later on be staged with the expected filenames.

@ ref_instances = $num_instances + $off_inst

#@ inst = 1
@ inst = 1 + $off_inst

echo $ref_instances' '$inst' '$off_inst

#while ( $inst <= $num_instances )
while ( $inst <= $ref_instances )

   set inst_string = `printf %04d $inst`

   # ===========================================================================
   set fname = "user_nl_datm_streams_${inst_string}"
   # ===========================================================================
   # DATM namelist
   # Create stream files for each ensemble member
   set SOURCEDIR = ${dartroot}/models/clm/shell_scripts/cesm2_3/spreads/d4o/GSWP
   ${COPY} ${SOURCEDIR}/${fname}         ${fname} || exit 5

   # ===========================================================================
   set fname = "user_nl_clm_${inst_string}"
   # ===========================================================================
   ${COPY} ${SOURCEDIR}/user_nl_clm_spreads        ${fname} || exit 5
  
  # ===========================================================================
   set fname = "user_nl_mosart_${inst_string}"
   # ===========================================================================

   # ===========================================================================
   set fname = "user_nl_datm_${inst_string}"
   # ===========================================================================
   
   # ===========================================================================
   set fname = "user_nl_rtm_${inst_string}"
   # ===========================================================================

   # ===========================================================================
   set fname = "user_nl_hydros_${inst_string}"
   # ===========================================================================
   echo "finidat_hydros = '/work/cmcc/lg07622/land/datain/refcase/cmcc/seasonal/2000/cm3_lndHIST_bgc_NoSnAg_eda1_hist.hydros_0021.r.2000-01-01-00000.nc'" >> ${fname}
   echo "flakinp_hydros = '/data/inputs/CESM/inputdata/lnd/clm2/rtmdata/LakMap_hydrosParam_0.5x0.5_c220204.nc'" >> ${fname}
   echo "frivinp_hydros = '/data/inputs/CESM/inputdata/lnd/clm2/rtmdata/rdirc_hydrosParam_0.5x0.5_c230927.nc'" >> ${fname}
   echo "ice_runoff = .false." >> ${fname}

   @ inst ++
end

./preview_namelists || exit 6

# ==============================================================================
# Stage the restarts now that the run directory exists
# ==============================================================================

echo "staging restarts"

set init_time = ${reftimestamp}

cat << EndOfText >! stage_cesm_files
#!/bin/csh -f
# This script can be used to help restart an experiment from any previous step.
# The appropriate files are copied to the RUN directory.
#
# Before running this script:
#  1) be sure CONTINUE_RUN is set correctly in the env_run.xml file in
#     your CASEROOT directory.
#     CONTINUE_RUN=FALSE => you are starting over at the initial time.
#     CONTINUE_RUN=TRUE  => you are starting from a previous step but not
#                           the very first one.
#  2) be sure 'restart_time' is set to the day and time that you want to
#     restart from if not the initial time.
#
#  3) be sure the prior inflation files are re-staged 
#     STAGE_INFLATION FALSE => no restage, default setting when case is first created
#     STAGE_INFLATION TRUE  => you are starting from a previous step or
#                              from the initial time            
#
#
#

set restart_time = $init_time
set STAGE_INFLATION = FALSE


# get the settings for this case from the CESM environment
cd ${caseroot}

setenv CONTINUE_RUN \`./xmlquery CONTINUE_RUN --value\`
setenv RUNDIR       \`./xmlquery RUNDIR       --value\`
setenv DOUT_S       \`./xmlquery DOUT_S       --value\`
setenv DOUT_S_ROOT  \`./xmlquery DOUT_S_ROOT  --value\`
setenv CASE         \`./xmlquery CASE         --value\`

cd \${RUNDIR}

echo 'Copying the required CESM files to the run directory to rerun'
echo 'a previous step.  CONTINUE_RUN from env_run.xml is' \${CONTINUE_RUN}
if ( \${CONTINUE_RUN} == TRUE ) then
  echo 'so files for some later step than the initial one will be restaged.'
  echo "Date to reset files to is: \${restart_time}"
else
  echo 'so files for the initial step of this experiment will be restaged.'
  echo "Date to reset files to is: ${init_time}"
endif
echo ''

if ( \${CONTINUE_RUN} == TRUE ) then

   #----------------------------------------------------------------------
   # This block copies over a set of restart files from any previous step of
   # the experiment that is NOT the initial step.
   # After running this script resubmit the job to rerun.
   #----------------------------------------------------------------------

   echo "Staging restart files for run date/time: " \${restart_time}

   #  The short term archiver is on, so the files we want should be in one
   #  of the short term archive 'rest' restart directories.  This assumes
   #  the long term archiver has NOT copied these files to the HPSS yet.

   if (  \${DOUT_S} == TRUE ) then

      # The restarts should be in the short term archive directory.

      set RESTARTDIR = \${DOUT_S_ROOT}/rest/\${restart_time}

      if ( ! -d \${RESTARTDIR} ) then

         echo "restart file directory not found: "
         echo " \${RESTARTDIR}"
         echo "If the long-term archiver is on, you may have to restore this directory first."
         echo "You can also check for either a .sta or a .sta2 hidden subdirectory in"
         echo "\${DOUT_S_ROOT}"
         echo "which may contain the 'rest' directory you need,"
         echo "and then modify RESTARTDIR in this script."
         exit 7

      endif

      ${COPY} \${RESTARTDIR}/* . || exit 7

   else

      # The short term archiver is off, which leaves all the restart files
      # in the run directory.  The rpointer files must still be updated to
      # point to the files with the right day/time.

      #@ inst=1
      @ inst = 1 + $off_inst
      #while (\$inst <= $num_instances)
      while (\$inst <= $ref_instances)

         set inst_string = \`printf _%04d \$inst\`

         echo "\${CASE}.cpl\${inst_string}.r.\${restart_time}.nc"    >! rpointer.cpl\${inst_string}
         echo "\${CASE}.clm2\${inst_string}.r.\${restart_time}.nc"   >! rpointer.lnd\${inst_string}
         echo "\${CASE}.datm\${inst_string}.r.\${restart_time}.nc"   >! rpointer.atm\${inst_string}
         echo "\${CASE}.datm\${inst_string}.rs1.\${restart_time}.nc" >> rpointer.atm\${inst_string}
         echo "\${CASE}.hydros\${inst_string}.r.\${restart_time}.nc" >! rpointer.rof\${inst_string}
         #echo "\${CASE}.mosart\${inst_string}.r.\${restart_time}.nc" >! rpointer.rof\${inst_string}

         @ inst ++
      end

      # If the multi-driver is not being used,
      # there is only a single coupler restart file.
      echo "\${CASE}.cpl.r.\${restart_time}.nc" >! rpointer.cpl

   endif

   echo "All files reset to rerun experiment step for time " \$restart_time

else     # CONTINUE_RUN == FALSE

   #----------------------------------------------------------------------
   # This block links the right files to rerun the initial (very first)
   # step of an experiment.  The names and locations are set during the
   # building of the case; to change them rebuild the case.
   # After running this script resubmit the job to rerun.
   #----------------------------------------------------------------------

   #@ inst=1
   @ inst = 1 + $off_inst
   #while (\$inst <= $num_instances)
   while (\$inst <= $ref_instances)

      set inst_string = \`printf _%04d \$inst\`

      #echo "Staging initial files for instance \$inst of $num_instances"
      echo "Staging initial files for instance \$inst of $ref_instances"

      if ( -e    ${stagedir}/${refcase}.clm2\${inst_string}.r.${init_time}.nc ) then
         ${LINK} ${stagedir}/${refcase}.clm2\${inst_string}.r.${init_time}.nc .
      else
         echo "ERROR: ${stagedir}/${refcase}.clm2\${inst_string}.r.${init_time}.nc does not exist."
         echo "       Check your 'reftimestamp' setting, or maybe your 'stagedir' or 'refcase' or ..."
         #exit 8
      endif

      if (-e     ${stagedir}/${refcase}.hydros\${inst_string}.r.${init_time}.nc ) then
         ${LINK} ${stagedir}/${refcase}.hydros\${inst_string}.r.${init_time}.nc .
      else
        echo "WARNING: ${stagedir}/${refcase}.hydros\${inst_string}.r.${init_time}.nc does not exist."
        echo "       Check your 'reftimestamp' setting, or maybe your 'stagedir' or 'refcase' or ..."
        echo "       If this is not a mistake, set finidat_rtm = ' ', within mosart namelist or input file"
      endif

      @ inst ++
   end

   echo "All files set to run the FIRST experiment step at time" $init_time

endif

   #----------------------------------------------------------------------
   # This block modifies the inflation rpointer files (priorinf_pointer_d{01-03}.txt)
   # such that the DART code uses the inflation files (clm_output_priorinf*.nc) from the 
   # previous time step (e.g. restart_time)
   # e.g. the following files:
   # clm_output_priorinf_mean_d01.2011-01-03-00000.nc
   # clm_output_priorinf_sd_d01.2011-01-03-00000.nc
   # would be used to apply inflation for time step: 2011-01-04
   #----------------------------------------------------------------------

if ( \${STAGE_INFLATION} == TRUE) then

# Confirm inflation is being used.

set  MYSTRING = \`grep inf_flavor input.nml\`
set  MYSTRING = \`echo \$MYSTRING | sed -e "s#[=,'\.]# #g"\`
set  PRIOR_INF = \$MYSTRING[2]
set  POSTE_INF = \$MYSTRING[3]

  if ( \$PRIOR_INF != 0 ) then

    if  ( \${CONTINUE_RUN} == FALSE) then
       # Generate cookie such that fill_inflation_restart 
       # generates inflation files

       date >! \${RUNDIR}/clm_inflation_cookie

    else  # CONTINUE_RUN=TRUE

         if ( ! -e priorinf_pointer_d01.txt ) then

         echo "ERROR: priorinf_pointer_d01.txt file not found"
         echo "At least 1 domain pointer file should exist if assimilation run is re-staged"
         echo "Prior inflation files will not be re-staged"
         exit 2

         endif

       @ domaincount = 0
       echo "     "
       echo "Re-setting priorinf pointer files for " \$restart_time
       echo "     "

     foreach POINTERFILE ( priorinf_pointer*.txt )

        @ domaincount ++

        set POINTERFILE = \`printf priorinf_pointer_d%02d.txt \$domaincount\`
        echo "Located inflation pointer file: " \$POINTERFILE
        set DOMAIN = \`printf _d%02d \$domaincount\`
        set FILE   = \`printf clm_output_priorinf_mean\${DOMAIN}.\${restart_time}.nc\`

         if ( ! -e \${FILE} ) then
         echo "ERROR: \${FILE} not found"
         echo "This file must exist to be inserted in \${POINTERFILE}"
         echo "Prior inflation file will not be re-staged"
         exit 3
         endif

        set SDFILE = \`echo \$FILE | sed -e "s#mean#sd#"\`
        echo "Inserting the prior inflation file into pointer: " \$FILE
        echo \$FILE   >! \$POINTERFILE
        echo \$SDFILE >> \$POINTERFILE

     end

     echo "The priorinf pointer files are reset to rerun experiment at: " \$restart_time
     echo "    "

    endif

  else   # \$PRIOR_INF==0

    echo "Warning: Prior inflation is turned off for this assimilation"
    echo "Inflation files will not be re-staged"
    echo "Check your input.nml inflation settings"

  endif

   if ( \$POSTE_INF != 0 ) then
      echo "ERROR: stage_cesm_files not configured to stage posterior inflation files."
      exit 4
   endif

endif

exit 0

EndOfText
chmod 0755 stage_cesm_files

./stage_cesm_files || exit 8

#===============================================================================
# This example has SourceMods that enable CLM to output solar induced fluorescence
# as an additional diagnostic variable ("FSIF") in the history file.
# There are also SourceMods that suppress the balance checks for the first
# restart timestep.

if ( ${use_SourceMods} == TRUE ) then

   if (    -d    ${SourceModDir} ) then
      ${COPY} -r ${SourceModDir}/* ${caseroot}/SourceMods/ || exit 7

      if ( -e    SourceMods/src.clm ) then
         cd      SourceMods/src.clm
         ${LINK} `find . -name "*F90"` . || exit 7
         cd      ../..
      endif
   else
      echo "ERROR - DART_params.csh use_SourceMods = ${use_SourceMods}"
      echo "ERROR - but there are no SourceMods in ${SourceModDir}"
      echo "        See discussion in DART_params.csh for information on"
      echo "        where to get a tar file of SourceMods for DART." 
      exit 7
   endif
endif

${BUILD_WRAPPER} ./case.build || exit 9

# ==============================================================================
# What to do next
# ==============================================================================

cat << EndOfText >! CESM_instructions.txt

-------------------------------------------------------------------------
Time to check the case.

Run the model by:

cd <LAND_SYSTEM_ROOT>/work_d4o/TEST_GSWP
./case.submit 	

-------------------------------------------------------------------------

EndOfText

cat CESM_instructions.txt

exit 0

