
SUBROUTINE BLACKHAT(YDODB,YDGP5,KTSLOT,YDSETINFO)

!**** SUBROUTINE BLACKHAT - CONTROLS BLACKLISTING

!          DRASKO VASILJEVIC ECMWF          21/10/1999

!*    PURPOSE
!     -------

!        CONTROLS IFS OBS. BLACKLISTING

!*    METHOD
!     ------

!        CONTROLS IFS OBSERVATION BLACKLISTING DECISION MAKING.
!     OBSERVATIONS ARE HANDLED IN SETS AS DEFINED IN ECSET.

!*    EXTERNALS
!     ---------

!        BLACK - BLACKLISTING

!**   MODIFICATIONS
!     -------------
!     04/06/23  C.Payan  : vue sur scat (JVIEW==3)
!     05/02/08  C.Payan  : appel BLACKCLN pour JVIEW==3
!     S. Healy  2004/10/27:  changed IBLACKVIEWS(8) for GPSRO processing
!     08/02/06  C. Facani : Add view for radars
!     07/04/10  A. Fouilloux: Add new codetype for MERIS
!     06/07/11  M. Rennie:  Add new obstype, NLIDAR
!     22/09/11  Antje Inness: Add new codetype for in-situ atm. compostion data
!     12-Jan-2012 A. Geer  : New obstype for all-sky 
!     25-May-2012 P. Poli  : Clean-up all non-CONV data from view no.1
!     19-Jul-2013 A. Geer  : Tidied SQLs to make this code slightly less dangerous
!     15-Mar-2016 A. Geer  : New sets (remove "THSAFE" sets), Gom plus
!     ------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB, JPRD
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE YOMLUN   , ONLY : NULOUT   ,NULERR
USE YOMCOCTP
USE OBSOP_SETS, ONLY : TYPE_SET_INFO
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
USE GOM_PLUS,  ONLY : TYPE_GOM_PLUS
USE DBASE_MOD, ONLY : DBASE
USE LL_MOD,    ONLY : LL
IMPLICIT NONE

CLASS(DBASE), INTENT(INOUT)     :: YDODB
TYPE(TYPE_GOM_PLUS), INTENT(IN) :: YDGP5
INTEGER(KIND=JPIM), INTENT(IN)  :: KTSLOT
TYPE(TYPE_SET_INFO),INTENT(IN)  :: YDSETINFO

TYPE(IFS_DBASE_VIEW)            :: ROBHDR,ROBODY
TYPE(LL)                        :: WHERE_CONDS
CHARACTER(LEN=3)                :: CL_JVIEW
CHARACTER(LEN=128)              :: CL_ROBHDR_SQL,CL_ROBODY_SQL
INTEGER(KIND=JPIM), PARAMETER   :: IBLACK_VIEWS=10
LOGICAL :: LL_USE_BLACK_VIEWS(IBLACK_VIEWS)
INTEGER(KIND=JPIM) :: IRET, INFO(1), IOBSTYPE,ICDTYP_TOVS,JVIEW,ISATGRP
INTEGER(KIND=JPIM) :: IREPCOUNT, ISENSOR
REAL(KIND=JPRB) :: ZHOOK_HANDLE

#include "abortdb.intfb.h"
#include "black.intfb.h"

!*
!     ------------------------------------------------------------------

!*       1.       START
!                 -----

IF (LHOOK) CALL DR_HOOK('BLACKHAT',0,ZHOOK_HANDLE)

IF (YDSETINFO%TSLOT /= -1 .AND. YDSETINFO%TSLOT /= KTSLOT) THEN
  WRITE(NULOUT,*)'*** SET=',YDSETINFO%ID,' DOES NOT HAVE ANYTHING TO DO WITH THE TIMESLOT=',KTSLOT
  IF (LHOOK) CALL DR_HOOK('BLACKHAT',1,ZHOOK_HANDLE)
  RETURN
ENDIF

IRET = 0

!           1.1   CODETYPE FOR THIS SET, ONLY SATEM DATA

IOBSTYPE    = YDSETINFO%OBSTYPE
ISATGRP     = YDSETINFO%GROUP
ICDTYP_TOVS = YDSETINFO%CODETYPE_SAT
ISENSOR     = YDSETINFO%SENSOR

!*
!     ------------------------------------------------------------------

!*       2.       MAKE INDEPENDENT BLACKLISTING DECISIONS
!                 ---------------------------------------

!           2.1   There are N ODB-views defined for BLACK, LOOP
!                 For reference, see ODB-sqls in files "odb/ddl.ECMA/black_*.sql"
!                 and -- of course -- the monster routine "odb/cma2odb/ctxinitdb.F90"
!                 (SS/15-Dec-2004)

LL_USE_BLACK_VIEWS(:) = .FALSE.

IF (IOBSTYPE == NSYNOP .OR.&
 &  IOBSTYPE == NAIREP .OR.&
 &  IOBSTYPE == NDRIBU .OR.&
 &  IOBSTYPE == NTEMP  .OR.&
 &  IOBSTYPE == NPILOT .OR.&
 &  IOBSTYPE == NPAOB) THEN
  LL_USE_BLACK_VIEWS(1) = .TRUE.
ELSEIF (IOBSTYPE == NSATOB) THEN
  LL_USE_BLACK_VIEWS(2) = .TRUE.
ELSEIF (IOBSTYPE == NSCATT) THEN
  LL_USE_BLACK_VIEWS(3) = .TRUE.
ELSEIF ((IOBSTYPE == NSATEM  .AND. ICDTYP_TOVS == NGTHRB) .OR.&
 &      (IOBSTYPE == NALLSKY .AND. ICDTYP_TOVS == NSSMI)) THEN
  LL_USE_BLACK_VIEWS(4) = .TRUE.
ELSEIF (IOBSTYPE == NSATEM .AND. ICDTYP_TOVS == NSTRESAT) THEN
  LL_USE_BLACK_VIEWS(7) = .TRUE.
ELSEIF (IOBSTYPE == NLIMB) THEN
  LL_USE_BLACK_VIEWS(8) = .TRUE.
ELSEIF (IOBSTYPE == NRADAR) THEN
  LL_USE_BLACK_VIEWS(9) = .TRUE.
ELSE
  ! Default for all other types of data
  LL_USE_BLACK_VIEWS(10) = .TRUE.
ENDIF

IREPCOUNT=0

DO JVIEW=1,IBLACK_VIEWS
  IF (.NOT.LL_USE_BLACK_VIEWS(JVIEW)) CYCLE

!           2.1.1 INITIALIZE DB (LOCAL; CONVENTIONAL REPs)

  CALL WHERE_CONDS%APPEND('$kset',     REAL(YDSETINFO%ID,JPRD))
  CALL WHERE_CONDS%APPEND('$tslot',    REAL(KTSLOT,JPRD))
  CALL WHERE_CONDS%APPEND('$obstype',  REAL(IOBSTYPE,JPRD))
  CALL WHERE_CONDS%APPEND('$codetype', REAL(ICDTYP_TOVS,JPRD))
  CALL WHERE_CONDS%APPEND('$sensor',   REAL(ISENSOR,JPRD))
 
  ! Construct required SQL view name
  WRITE(CL_JVIEW,"(I3)") JVIEW
  WRITE(CL_ROBHDR_SQL,'(A,A)') "black_robhdr_", ADJUSTL(CL_JVIEW)
  WRITE(CL_ROBODY_SQL,'(A,A)') "black_robody_", ADJUSTL(CL_JVIEW)

  ! Run the SQL
  IRET = YDODB%SELECT(TRIM(CL_ROBODY_SQL),  ROBODY,  PARAMS_LL=WHERE_CONDS)
  IRET = YDODB%SELECT(TRIM(CL_ROBHDR_SQL),  ROBHDR,  PARAMS_LL=WHERE_CONDS)  ! hdr must come last for iret

  CALL ROBHDR%SETUP_COL_POINTERS()
  CALL ROBODY%SETUP_COL_POINTERS()
  CALL ROBODY%SETUP_REPORT_INDICES()

  IREPCOUNT = IREPCOUNT+IRET
  IF(IRET /= 0) THEN
    CALL BLACKHAT_CHECK_ERROR(JVIEW)

!           2.1.2 BLACKLISTING

    CALL BLACK(ROBHDR,ROBODY,YDGP5,YDSETINFO,IRET)

  ENDIF

!           2.1.3 PUT THE ODB VIEW AWAY

  IF(ALLOCATED(ROBHDR%DATA))  IRET = YDODB%PUT(ROBHDR)
  IF(ALLOCATED(ROBODY%DATA))  IRET = YDODB%PUT(ROBODY)
  CALL WHERE_CONDS%DESTROY()

!           2.1.4 END LOOP OVER ODB VIEWS
ENDDO

IF (LHOOK) CALL DR_HOOK('BLACKHAT',1,ZHOOK_HANDLE)

! -------------------------------------------------------------------

CONTAINS

SUBROUTINE BLACKHAT_CHECK_ERROR(KCASE)
IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(IN) :: KCASE
REAL(KIND=JPRB) :: ZHOOK_HANDLE
#include "abortdb.intfb.h"
IF (LHOOK) CALL DR_HOOK('BLACKHAT:BLACKHAT_CHECK_ERROR',0,ZHOOK_HANDLE)
IF(IRET /= YDSETINFO%LNSET ) THEN
  WRITE(NULERR,'(a,i1,a)') '*** ERROR IN BLACK(',KCASE,')'
  WRITE(NULERR,'(''     SLOT: '',I10)') KTSLOT
  WRITE(NULERR,'(''     SET : '',I10)') YDSETINFO%ID
  WRITE(NULERR,'(''     IRET: '',I10)') IRET
  WRITE(NULERR,'(''     MLNSET'',I10)') YDSETINFO%LNSET
  CALL FLUSH(NULOUT)
  CALL ABORTDB('BLACK','IRET AND MLNSET ARE NOT EQUAL',KCASE)
ENDIF
IF (LHOOK) CALL DR_HOOK('BLACKHAT:BLACKHAT_CHECK_ERROR',1,ZHOOK_HANDLE)
END SUBROUTINE BLACKHAT_CHECK_ERROR

END SUBROUTINE BLACKHAT
