MODULE YOMBLINIT

USE PARKIND1  ,ONLY : JPIM

IMPLICIT NONE

SAVE

!*     YOMBLINIT - BLACKLIST INITIALIZATION
!                        SETUP IN SUBROUTINE*BLINIT

!        HEIKKI JARVINEN   ECMWF     15/3/95

!     NAME      TYPE                  MEANING
!     ----      ----                  -------

!     NBHEAD       I    NO. INTERFACE VARIABLES RELATED TO OBSERVATION HEADER
!     NBBODY       I    NO. INTERFACE VARIABLES RELATED TO OBSERVATION BODY
!     NBDATA       I    TOTAL NO. INTERFACE VARIABLES 
!     NFEEDBACK    I    LENGTH OF THE BLACKLIST FEEDBACK VECTOR

INTEGER(KIND=JPIM) :: NBHEAD
INTEGER(KIND=JPIM) :: NBBODY
INTEGER(KIND=JPIM) :: NBDATA
INTEGER(KIND=JPIM) :: NFEEDBACK

!-----------------------------------------------------------------------

END MODULE YOMBLINIT
