MODULE PARDIMO

USE PARKIND1  ,ONLY : JPIM

IMPLICIT NONE

SAVE

!****-------------------------------------------------------------------
!****  CD PARDIMO : PARAMETERS RELATED TO OBSERVATIONS
!****  ----------
!****  Auteurs    : J.PAILLEUX, D.VASILJEVIC, P.CAILLE    90/05-91/09
!****-------------------------------------------------------------------
!*  OBSERVATIONS ARRAYS DIMENSIONS
!*  ------------------------------
!*    JPNOTP  : MAXIMUM NUMBER OF OBSERVATIONS TYPES
!*    JPXTIM  : MAXIMUM NUMBER OF TIME SLOTS
!*
!*  OBSERVATIONS PROCESSING
!*  -----------------------
!*    JPXSOBT : MAXIMUM NUMBER OF SUB-OBSERVATIONS TYPES
!*    JPXVAR  : MAXIMUM NUMBER OF VARIABLES
!*    JPXAREA : MAXIMUM NUMBER OF AREAS
!*    JPHUBLEV: NUMBER OF DIFFERENT HUBER LAYERS IN THE VERTICAL
!*              (STRATOSPHERE=1,TROPOSPHERE=2,BOUNDARY LAYER=3) 
!*    JPXAMVPROD: MAXIMUM NUMBER OF AMV(SATAM) PRODUCERS
!*
!****-------------------------------------------------------------------
INTEGER(KIND=JPIM), PARAMETER :: JPNOTP=18
INTEGER(KIND=JPIM), PARAMETER :: JPXTIM=99

INTEGER(KIND=JPIM), PARAMETER :: JPXSOBT=3
INTEGER(KIND=JPIM), PARAMETER :: JPXVAR=61
INTEGER(KIND=JPIM), PARAMETER :: JPXAREA=20

INTEGER(KIND=JPIM), PARAMETER :: JPHUBLEV=3
INTEGER(KIND=JPIM), PARAMETER :: JPXAMVPROD=10
!****-------------------------------------------------------------------
END MODULE PARDIMO
