
MODULE PARERR

USE PARKIND1  ,ONLY : JPIM

IMPLICIT NONE

SAVE

!*    PARERR - OBS. ERRORS VARIOUS PARAMETERS

!        D. VASILJEVIC    ECMWF    19/09/94

!     NAME                    MEANING
!     ----                    -------
!     JPMXESLV    MAX. NO. OF ERROR STANDARD LEVELS
!     JPMXESLY    MAX. NO. OF ERROR STANDARD LAYERS
!     JPMXEARE    MAX. NO. ERROR AREAS

INTEGER(KIND=JPIM), PARAMETER :: JPMXESLV=15
INTEGER(KIND=JPIM), PARAMETER :: JPMXESLY=14
INTEGER(KIND=JPIM), PARAMETER :: JPMXEARE=3

!-----------------------------------------------------------------------

END MODULE PARERR
