MODULE YOMCOCTP
!ODB SET $SYNOP = 1
!ODB SET $AIREP = 2
!ODB SET $SATOB = 3
!ODB SET $DRIBU = 4
!ODB SET $TEMP = 5
!ODB SET $PILOT = 6
!ODB SET $SATEM = 7
!ODB SET $ATOVS = 210
!ODB SET $RTOVS = 211
!ODB SET $TOVS = 212
!ODB SET $SSMI = 215
!ODB SET $SMOS = 400
!ODB SET $PAOB = 8
!ODB SET $SCATT = 9
!ODB SET $LIMB = 10
!ODB SET $ISAC = 11
!ODB SET $RALT = 12
!ODB SET $RADAR = 13
!ODB SET $GBRAD = 14
!ODB SET $LIDAR = 15
!ODB SET $RAINGG = XXX???
!ODB SET $BG = 1
!ODB SET $ADJ = 2

USE PARKIND1, ONLY : JPIM     ,JPRB
USE PARDIMO , ONLY : JPNOTP
USE PARCMA  , ONLY : JPMXOTP

IMPLICIT NONE

SAVE

PUBLIC SUCOCTP

!*     YOMCOCTP - CMA OBS./CODE TYPES

!        D. VASILJEVIC   ECMWF     15/09/94

!     MODIFICATONS
!     ------------
!       23/12/2004   Niels Bormann  RARAD becomes LIMB; new code types for LIMB
!       24/04/2009   Joaquin Munoz Sabater  New code types for SMOS L-band radiances
!       05/08/2010   P. Lopez  New code types for ground-based RADAR rain rate
!       05/08/2010   P. Lopez  New code types for ground-based RADAR rain rate
!       16/05/2011   P. de Rosnay New code type for additional land data
!       03/06/2011   M. Rennie New obs type for LIDAR, with DWL code type moved to
!                    LIDAR
!       08/06/2011   S. Abdalla             New code types for Radar Altimeter
!       22/09/2011   Antje Inness New code type for in-situ atmospheric compositon data
!      03-Jan-2012   A. Geer   New obstype for all-sky satellite  radiances
!      22-Aug-2012   P. Lopez  New obstype for rain gauge data
!      28-Jan-2014   T. Kral   New codetypes for TAMDAR, ACARS with mixing ratio,
!                    BUFR PILOT and BUFR SYNOP
!      10-Jan-2017   S. de Haan  New code type for Mode-S EHS
!     CMA OBS./CODE TYPES

!     NAME        TYPE                   MEANING
!     ----        ----                   -------
!     NOOBST        I      NO. OF OBS. TYPES
!     NOCODT        I      NO. OF OBS. CODE TYPES
!     NSYNOP        I      SYNOP
!     NSYNOPSQ      I      SYNOP
!     NSYNCT        I      NO. OF SYNOP CODE TYPES
!     NSRSCD        I      SYNOP LAND REPORT
!     NSRSCDSQ      I      SYNOP LAND REPORT SQ. NO.
!     NATSCD        I      SYNOP LAND AUTOMATIC REPORT
!     NATSCDSQ      I      SYNOP LAND AUTOMATIC REPORT SQ. NO.
!     NADSCD        I      ADDITIONAL LAND REPORT
!     NADSCDSQ      I      ADDITIONAL LAND REPORT SQ. NO.
!     NSHSCD        I      SYNOP-SHIP REPORT
!     NSHSCDSQ      I      SYNOP-SHIP REPORT SQ. NO.
!     NABSCD        I      SYNOP-SHIP ABBREVIATED REPORT
!     NABSCDSQ      I      SYNOP-SHIP ABBREVIATED REPORT SQ. NO.
!     NSHRED        I      SYNOP SHRED REPORT
!     NSHREDSQ      I      SYNOP SHRED REPORT SQ. NO.
!     NATSHS        I      SYNOP AUTOMATIC SHIP REPORT
!     NATSHSSQ      I      SYNOP AUTOMATIC SHIP REPORT SQ. NO.
!     NSYRCD        I      SYNOR REPORT
!     NSYRCDSQ      I      SYNOR REPORT SQ. NO.
!     NRADOH        I      RADOME
!     NRADOHSQ      I      RADOME SQ. NO.
!     NMETAR        I      METAR
!     NMETARSQ      I      METAR SQ. NO.
!     NPGPS         I      Ground-based GPS
!     NPGPSSQ       I      Ground-based GPS SQ. NO.
!     NAIREP        I      AIREP
!     NAIREPSQ      I      AIREP
!     NAIRCT        I      NO. OF AIREP CODE TYPES
!     NAIRCD        I      AIRCRAFT REPORT
!     NAIRCDSQ      I      AIRCRAFT REPORT SQ. NO.
!     NCODAR        I      CODAR REPORT
!     NCODARSQ      I      CODAR REPORT SQ. NO.
!     NCOLBA        I      COLBA REPORT
!     NCOLBASQ      I      COLBA REPORT SQ. NO.
!     NAMDAR        I      AMDAR AIRCRAFT REPORT
!     NAMDARSQ      I      AMDAR AIRCRAFT REPORT SQ. NO.
!     NACARS        I      ACARS AIRCRAFT REPORT
!     NACARSSQ      I      ACARS AIRCRAFT REPORT SQ. NO.
!     NWAMDAR       I      WIGOS AMDAR AIRCRAFT REPORT
!     NWAMDARSQ     I      WIGOS AMDAR AIRCRAFT REPORT SQ. NO.
!     NMDEHS        I      MODE-S EHS OBS REPORT
!     NMDEHSSQ      I      MODE-S EHS OBS REPORT SQ. NO.
!     NAADSC        I      ADS-C AIRCRAFT REPORT
!     NAADSCSQ      I      ADS-C AIRCRAFT REPORT SQ. NO.
!     NSIMAI        I      SIMULATED AIREP REPORT
!     NSIMAISQ      I      SIMULATED AIREP REPORT SQ. NO.
!     NSATOB        I      SATOB
!     NSATOBSQ      I      SATOB
!     NSABCT        I      NO. OF SATOB CODE TYPES
!     NSTBCD        I      SATOB REPORT
!     NSTBCDSQ      I      SATOB REPORT SQ. NO.
!     NSTB86        I      HIGH RES. VIS WIND SATOB REPORT
!     NSTB86SQ      I      HIGH RES. VIS WIND SATOB REPORT SQ. NO.
!     NSTB87        I      AMV REPORT
!     NSTB87SQ      I      AMV REPORT SQ. NO.
!     NSST          I      SST REPORT
!     NSSTSQ        I      SST REPORT SQ. NO.
!     NDRIBU        I      DRIBU
!     NDRIBUSQ      I      DRIBU
!     NDRICT        I      NO. OF DRIBU CODE TYPES
!     NDRBCD        I      DRIBU REPORT
!     NDRBCDSQ      I      DRIBU REPORT SQ. NO.
!     NBATHY        I      BATHY REPORT
!     NBATHYSQ      I      BATHY REPORT SQ. NO.
!     NTESAC        I      TESAC REPORT
!     NTESACSQ      I      TESAC REPORT SQ. NO.
!     NDERS1        I      ERS1 AS DRIBU
!     NDERS1SQ      I      ERS1 AS DRIBU SQ. NO.
!     NBUOYM        I      MOORED BUOY REPORT
!     NBUOYMSQ      I      MOORED BUOY REPORT SQ. NO.
!     NBUOYD        I      DRIFTING BUOY REPORT
!     NBUOYDSQ      I      DRIFTING BUOY REPORT SQ. NO.
!     NTEMP         I      TEMP
!     NTEMPSQ       I      TEMP
!     NTEMCT        I      NO. OF TEMP CODE TYPES
!     NLDTCD        I      LAND TEMP REPORT
!     NLDTCDSQ      I      LAND TEMP REPORT SQ. NO.
!     NSHTCD        I      TEMP SHIP REPORT
!     NSHTCDSQ      I      TEMP SHIP REPORT SQ. NO.
!     NTDROP        I      TEMP-DROP REPORT
!     NTDROPSQ      I      TEMP-DROP REPORT SQ. NO.
!     NROCOB        I      ROCOB REPORT
!     NROCOBSQ      I      ROCOB REPORT SQ. NO.
!     NROCSH        I      ROCOB SHIP REPORT
!     NROCSHSQ      I      ROCOB SHIP REPORT SQ. NO.
!     NMBTMP        I      MOBILE TEMP REPORT
!     NMBTMPSQ      I      MOBILE TEMP REPORT SQ. NO.
!     NSIMTE        I      SIMULATED TEMP
!     NSIMTESQ      I      SIMULATED TEMP SQ. NO.
!     NLBTEM        I      BUFR LAND TEMP
!     NLBTEMSQ      I      BUFR LAND TEMP SQ. NO.
!     NSBTEM        I      BUFR SHIP TEMP
!     NSBTEMSQ      I      BUFR SHIP TEMP SQ. NO.
!     NDBTEM        I      BUFR TEMP DROP
!     NDBTEMSQ      I      BUFR TEMP DROP SQ. NO.
!     NFBTEM        I      BUFR TEMP DESCENT
!     NFBTEMSQ      I      BUFR TEMP DESCENT SQ. NO.
!     NPILOT        I      PILOT
!     NPILOTSQ      I      PILOT
!     NPILCT        I      NO. OF PILOT CODE TYPES
!     NLDPCD        I      LAND PILOT REPORT
!     NLDPCDSQ      I      LAND PILOT REPORT SQ. NO.
!     NSHPCD        I      SHIP PILOT REPORT
!     NSHPCDSQ      I      SHIP PILOT REPORT SQ. NO.
!     NWPPCD        I      AMERICAN WIND PROFILERS
!     NWPPCDSQ      I      AMERICAN WIND PROFILERS SQ. NO.
!     NEWPPCD       I      EUROPEAN WIND PROFILERS
!     NEWPPCDSQ     I      EUROPEAN WIND PROFILERS SQ. NO.
!     NJWPPCD       I      JAPANESE WIND PROFILERS
!     NJWPPCDSQ     I      JAPANESE WIND PROFILERS SQ. NO.
!     NMBPLT        I      MOBILE WIND PILOT
!     NSATEM        I      SATEM
!     NSATEMSQ      I      SATEM
!     NSAMCT        I      NO. OF SATEM CODE TYPES
!     NSTMCD        I      SATEM REPORT
!     NSTMCDSQ      I      SATEM REPORT SQ. NO.
!     NSTOVS        I      HIGH RESOLUTION SATELLITE REPORT
!     NSTOVSSQ      I      HIGH RESOLUTION SATELLITE REPORT SQ. NO.
!     NSTRESAT      I      RETRIEVED OZONE LAYERS REPORT
!     NSTRESATSQ    I      RETRIEVED OZONE LAYERS REPORT SQ. NO.
!     NSTDWL        I      HIGH RES. SIMUL. DWL SAT. REPORT
!     NSTDWLSQ      I      HIGH RES. SIMUL. DWL SAT. REPORT SQ. NO.
!     NSTTOV        I      HIGH RES. SIMUL. TOVS SAT. REPORT
!     NSTTOVSQ      I      HIGH RES. SIMUL. TOVS SAT. REPORT SQ. NO.
!     NGTSTB        I      GTS BUFR SATEM REPORT (250 KM TEMP. AND
!                          HUM. PROFILES)
!     NGTSTBSQ      I      GTS BUFR SATEM REPORT (250 KM TEMP. AND
!                          HUM. PROFILES) SQ. NO.
!     NGTST1        I      GTS BUFR SATEM CLEAR RAD. REPORT
!     NGTST1SQ      I      GTS BUFR SATEM CLEAR RAD. REPORT SQ. NO.
!     NGTST2        I      GTS BUFR SATEM RETR PROFILES AND
!                          CLEAR RADIANCES REPORT
!     NGTST2SQ      I      GTS BUFR SATEM RETR PROFILES AND
!                          CLEAR RADIANCES REPORT SQ. NO.
!     NGTHRB        I      HIGH RES. 80 KM BUFR NON GTS SATEM RETR.
!                          PROFILES
!     NGTHRBSQ      I      HIGH RES. 80 KM BUFR NON GTS SATEM RETR.
!                          PROFILES SQ. NO.
!     NGTHR1        I      HIGH RES 80 KM BUFR NON GTS SATEM CLEAR
!                          RADIANCE REPORT
!     NGTHR1SQ      I      HIGH RES 80 KM BUFR NON GTS SATEM CLEAR
!                          RADIANCE REPORT SQ. NO.
!     NGTHR2        I      HIGH RES 80 KM BUFR NON GTS SATEM PROFILES
!                          AND CLEAR RADIANCE REPORT
!     NGTHR2SQ      I      HIGH RES 80 KM BUFR NON GTS SATEM PROFILES
!                          AND CLEAR RADIANCE REPORT SQ. NO.
!     NSSMI         I      SSMI REPORT
!     NSSMISQ       I      SSMI REPORT SQ. NO.
!     NPAOB         I      PAOB
!     NPAOBSQ       I      PAOB
!     NPAOCT        I      NO. OF PAOB CODE TYPES
!     NPABCD        I      PAOB REPORT
!     NPABCDSQ      I      PAOB REPORT SQ. NO.
!     NTYPHO        I      CYCLON REPORT
!     NTYPHOSQ      I      CYCLON REPORT SQ. NO.
!     NSCATT        I      SCATTEROMETER
!     NSCATTSQ      I      SCATTEROMETER
!     NSCACT        I      NO. OF SCATTEROMETER CODE TYPES
!     NSCAT1        I      SCATTEROMETER CODE TYPE 1
!     NSCAT1SQ      I      SCATTEROMETER CODE TYPE 1 SQ. NO.
!     NSCAT2        I      SCATTEROMETER CODE TYPE 2
!     NSCAT2SQ      I      SCATTEROMETER CODE TYPE 2 SQ. NO.
!     NSCAT3        I      SCATTEROMETER CODE TYPE 3
!     NSCAT3SQ      I      SCATTEROMETER CODE TYPE 3 SQ. NO.
!     NSCAT4        I      SCATTEROMETER CODE TYPE 4
!     NSCAT4SQ      I      SCATTEROMETER CODE TYPE 4 SQ. NO.
!     NSCAT5        I      SCATTEROMETER CODE TYPE 5
!     NSCAT5SQ      I      SCATTEROMETER CODE TYPE 5 SQ. NO.
!     NSCAT6        I      SCATTEROMETER CODE TYPE 6
!     NSCAT6SQ      I      SCATTEROMETER CODE TYPE 6 SQ. NO.
!     NSCAT7        I      SCATTEROMETER CODE TYPE 7
!     NSCAT7SQ      I      SCATTEROMETER CODE TYPE 7 SQ. NO.
!     NSCAT8        I      SCATTEROMETER CODE TYPE 8
!     NSCAT8SQ      I      SCATTEROMETER CODE TYPE 8 SQ. NO.
!     NLIMB         I      LIMB OBSERVATIONS
!     NLIMBSQ       I      LIMB OBSERVATIONS
!     NLIMBCT       I      NO. LIMB OBSERVATION CODE TYPES
!     NRALT         I      RADAR ALTIMETER
!     NRALTSQ       I      RADAR ALTIMETER
!     NRALTCT       I      NO. OF RADAR ALTIMETER CODE TYPES
!     NGPSRO        I      GPS RADIO OCCULTATION CODE TYPE
!     NRALT1        I      RADAR ALTIMETER CODE TYPE 1
!     NRALT1SQ      I      RADAR ALTIMETER CODE TYPE 1 SQ. NO.
!     NRALT2        I      RADAR ALTIMETER CODE TYPE 2
!     NRALT2SQ      I      RADAR ALTIMETER CODE TYPE 2 SQ. NO.
!     NRALT3        I      RADAR ALTIMETER CODE TYPE 3
!     NRALT3SQ      I      RADAR ALTIMETER CODE TYPE 3 SQ. NO.
!     NRALT4        I      RADAR ALTIMETER CODE TYPE 4
!     NRALT4SQ      I      RADAR ALTIMETER CODE TYPE 4 SQ. NO.
!     NRALT5        I      RADAR ALTIMETER CODE TYPE 5
!     NRALT5SQ      I      RADAR ALTIMETER CODE TYPE 5 SQ. NO.
!     NGPSROSQ      I      GPS RADIO OCCULTATION SQ. NO.
!     NLRAD         I      LIMB RADIANCES CODE TYPE
!     NLRADSQ       I      LIMB RADIANCES SQ. NO.
!     NRADAR        I      RADAR
!     NRADARSQ      I      RADAR SQ. NO
!     NRADA1        I      RADAR CODE TYPE 1
!     NRADA1SQ      I      RADAR CODE TYPE 1 SQ. NO.
!     NSMOS         I      SMOS CODE TYPE
!     NSMOSSQ       I      SMOS CODE TYPE SQ. NO.
!     NTCWC         I      TCWC (MERIS) CODE TYPE
!     NTCWCSQ       I      TCWC(MERIS) CODE TYPe SQ. NO.
!     NGBRAD        I      GROUND-BASED RADAR
!     NGBRADSQ      I      GROUND-BASED RADAR SQ. NO
!     NGBRADCT      I      NO. OF GROUND-BASED RADAR CODE TYPES (ECMWF)
!     NRADRR        I      GROUND-BASED RADAR RAIN RATE
!     NRADRRSQ      I      GROUND-BASED RADAR RAIN RATE SQ. NO.
!     NISAC         I      ISAC
!     NISACSQ       I      ISAC SQ. NO
!     NISACCT       I      NO. ISAC OBSERVATION CODE TYPES
!     NISAC1        I      ISAC CODE TYPE 1
!     NISAC1SQ      I      ISAC CODE TYPE 1 SQ. NO.
!     NLIDAR        I      LIDAR OBSERVATIONS
!     NLIDARSQ      I      LIDAR OBSERVATIONS
!     NLIDARCT      I      NO. LIDAR OBSERVATION CODE TYPES
!     NDWLPCD       I      DOPPLER WIND LIDAR CODE TYPE
!     NDWLPCDSQ     I      DOPPLER WIND LIDAR CODE TYPE SQ. NO.
!     NRAINGG       I      RAIN GAUGE DATA
!     NRAINGGSQ     I      RAIN GAUGE DATA SQ. NO
!     NRAINGGCT     I      NO. OF RAIN GAUGE DATA CODE TYPES (ECMWF)
!     NTAMDAR       I      TAMDAR AIRCRAFT REPORT
!     NTAMDARSQ     I      TAMDAR AIRCRAFT REPORT SQ. NO.
!     NACARSMR      I      ACARS WITH MIXING RATIO
!     NACARSMRSQ    I      ACARS WITH MIXING RATIO SQ. NO.
!     NBLDPCD       I      BUFR LAND PILOT
!     NBLDPCDSQ     I      BUFR LAND PILOT SQ. NO.
!     NBSHPCD       I      BUFR SHIP PILOT
!     NBSHPCDSQ     I      BUFR SHIP PILOT SQ. NO.
!     NBLSCD        I      BUFR LAND SYNOP
!     NBLSCDSQ      I      BUFR LAND SYNOP SQ. NO.
!     NBSSCD        I      BUFR SHIP SYNOP
!     NBSSCDSQ      I      BUFR SHIP SYNOP SQ. NO.

INTEGER(KIND=JPIM), PARAMETER :: NOOBST   =  JPMXOTP
INTEGER(KIND=JPIM), PARAMETER :: NOCODT   =  13
INTEGER(KIND=JPIM), PARAMETER :: NSYNOP   =   1
INTEGER(KIND=JPIM), PARAMETER :: NSYNOPSQ =  1
INTEGER(KIND=JPIM), PARAMETER :: NSYNCT   =  13
INTEGER(KIND=JPIM), PARAMETER :: NSRSCD   =  11
INTEGER(KIND=JPIM), PARAMETER :: NSRSCDSQ =   1
INTEGER(KIND=JPIM), PARAMETER :: NATSCD   =  14
INTEGER(KIND=JPIM), PARAMETER :: NATSCDSQ =   2
INTEGER(KIND=JPIM), PARAMETER :: NSHSCD   =  21
INTEGER(KIND=JPIM), PARAMETER :: NSHSCDSQ =   3
INTEGER(KIND=JPIM), PARAMETER :: NABSCD   =  22
INTEGER(KIND=JPIM), PARAMETER :: NABSCDSQ =   4
INTEGER(KIND=JPIM), PARAMETER :: NSHRED   =  23
INTEGER(KIND=JPIM), PARAMETER :: NSHREDSQ =   5
INTEGER(KIND=JPIM), PARAMETER :: NATSHS   =  24
INTEGER(KIND=JPIM), PARAMETER :: NATSHSSQ =   6
INTEGER(KIND=JPIM), PARAMETER :: NSYRCD   =  15
INTEGER(KIND=JPIM), PARAMETER :: NSYRCDSQ =   7
INTEGER(KIND=JPIM), PARAMETER :: NRADOH   =  16
INTEGER(KIND=JPIM), PARAMETER :: NRADOHSQ =   8
INTEGER(KIND=JPIM), PARAMETER :: NMETAR   = 140
INTEGER(KIND=JPIM), PARAMETER :: NMETARSQ =   9
INTEGER(KIND=JPIM), PARAMETER :: NPGPS    = 110
INTEGER(KIND=JPIM), PARAMETER :: NPGPSSQ  =  10
INTEGER(KIND=JPIM), PARAMETER :: NADSCD   =  17
INTEGER(KIND=JPIM), PARAMETER :: NADSCDSQ =  11
INTEGER(KIND=JPIM), PARAMETER :: NBLSCD   = 170
INTEGER(KIND=JPIM), PARAMETER :: NBLSCDSQ =  12
INTEGER(KIND=JPIM), PARAMETER :: NBSSCD   = 182
INTEGER(KIND=JPIM), PARAMETER :: NBSSCDSQ =  13
INTEGER(KIND=JPIM), PARAMETER :: NAIREP   =   2
INTEGER(KIND=JPIM), PARAMETER :: NAIREPSQ =   2
INTEGER(KIND=JPIM), PARAMETER :: NAIRCT   =  11
INTEGER(KIND=JPIM), PARAMETER :: NAIRCD   = 141
INTEGER(KIND=JPIM), PARAMETER :: NAIRCDSQ =   1
INTEGER(KIND=JPIM), PARAMETER :: NCODAR   =  41
INTEGER(KIND=JPIM), PARAMETER :: NCODARSQ =   2
INTEGER(KIND=JPIM), PARAMETER :: NCOLBA   = 241
INTEGER(KIND=JPIM), PARAMETER :: NCOLBASQ =   3
INTEGER(KIND=JPIM), PARAMETER :: NAMDAR   = 144
INTEGER(KIND=JPIM), PARAMETER :: NAMDARSQ =   4
INTEGER(KIND=JPIM), PARAMETER :: NACARS   = 145
INTEGER(KIND=JPIM), PARAMETER :: NACARSSQ =   5
INTEGER(KIND=JPIM), PARAMETER :: NSIMAI   = 142
INTEGER(KIND=JPIM), PARAMETER :: NSIMAISQ =   6
INTEGER(KIND=JPIM), PARAMETER :: NTAMDAR  = 148
INTEGER(KIND=JPIM), PARAMETER :: NTAMDARSQ=   7
INTEGER(KIND=JPIM), PARAMETER :: NACARSMR = 149
INTEGER(KIND=JPIM), PARAMETER :: NACARSMRSQ=  8
INTEGER(KIND=JPIM), PARAMETER :: NWAMDAR  = 146
INTEGER(KIND=JPIM), PARAMETER :: NWAMDARSQ=   9
INTEGER(KIND=JPIM), PARAMETER :: NMDEHS   = 147
INTEGER(KIND=JPIM), PARAMETER :: NMDEHSSQ =  10
INTEGER(KIND=JPIM), PARAMETER :: NAADSC   = 151
INTEGER(KIND=JPIM), PARAMETER :: NAADSCSQ =  11
INTEGER(KIND=JPIM), PARAMETER :: NSATOB   =   3
INTEGER(KIND=JPIM), PARAMETER :: NSATOBSQ =   3
INTEGER(KIND=JPIM), PARAMETER :: NSABCT   =   4
INTEGER(KIND=JPIM), PARAMETER :: NSTBCD   =  88
INTEGER(KIND=JPIM), PARAMETER :: NSTBCDSQ =   1
INTEGER(KIND=JPIM), PARAMETER :: NSTB86   =  89
INTEGER(KIND=JPIM), PARAMETER :: NSTB86SQ =   2
INTEGER(KIND=JPIM), PARAMETER :: NSTB87   =  90
INTEGER(KIND=JPIM), PARAMETER :: NSTB87SQ =   4
INTEGER(KIND=JPIM), PARAMETER :: NSST     = 188
INTEGER(KIND=JPIM), PARAMETER :: NSSTSQ   =   3
INTEGER(KIND=JPIM), PARAMETER :: NDRIBU   =   4
INTEGER(KIND=JPIM), PARAMETER :: NDRIBUSQ =   4
INTEGER(KIND=JPIM), PARAMETER :: NDRICT   =   6
INTEGER(KIND=JPIM), PARAMETER :: NDRBCD   = 165
INTEGER(KIND=JPIM), PARAMETER :: NDRBCDSQ =   1
INTEGER(KIND=JPIM), PARAMETER :: NBATHY   =  63
INTEGER(KIND=JPIM), PARAMETER :: NBATHYSQ =   2
INTEGER(KIND=JPIM), PARAMETER :: NTESAC   =  64
INTEGER(KIND=JPIM), PARAMETER :: NTESACSQ =   3
INTEGER(KIND=JPIM), PARAMETER :: NDERS1   = 160
INTEGER(KIND=JPIM), PARAMETER :: NDERS1SQ =   4
INTEGER(KIND=JPIM), PARAMETER :: NBUOYM   = 188
INTEGER(KIND=JPIM), PARAMETER :: NBUOYMSQ =   5
INTEGER(KIND=JPIM), PARAMETER :: NBUOYD   = 189
INTEGER(KIND=JPIM), PARAMETER :: NBUOYDSQ =   6
INTEGER(KIND=JPIM), PARAMETER :: NTEMP    =   5
INTEGER(KIND=JPIM), PARAMETER :: NTEMPSQ  =   5
INTEGER(KIND=JPIM), PARAMETER :: NTEMCT   =  11
INTEGER(KIND=JPIM), PARAMETER :: NLDTCD   =  35
INTEGER(KIND=JPIM), PARAMETER :: NLDTCDSQ =   1
INTEGER(KIND=JPIM), PARAMETER :: NSHTCD   =  36
INTEGER(KIND=JPIM), PARAMETER :: NSHTCDSQ =   2
INTEGER(KIND=JPIM), PARAMETER :: NTDROP   = 135
INTEGER(KIND=JPIM), PARAMETER :: NTDROPSQ =   3
INTEGER(KIND=JPIM), PARAMETER :: NROCOB   =  39
INTEGER(KIND=JPIM), PARAMETER :: NROCOBSQ =   4
INTEGER(KIND=JPIM), PARAMETER :: NROCSH   =  40
INTEGER(KIND=JPIM), PARAMETER :: NROCSHSQ =   5
INTEGER(KIND=JPIM), PARAMETER :: NMBTMP   =  37
INTEGER(KIND=JPIM), PARAMETER :: NMBTMPSQ =   6
INTEGER(KIND=JPIM), PARAMETER :: NSIMTE   = 137
INTEGER(KIND=JPIM), PARAMETER :: NSIMTESQ =   7
INTEGER(KIND=JPIM), PARAMETER :: NLBTEM   = 109
INTEGER(KIND=JPIM), PARAMETER :: NLBTEMSQ =   8
INTEGER(KIND=JPIM), PARAMETER :: NSBTEM   = 111
INTEGER(KIND=JPIM), PARAMETER :: NSBTEMSQ =   9
INTEGER(KIND=JPIM), PARAMETER :: NDBTEM   = 230
INTEGER(KIND=JPIM), PARAMETER :: NDBTEMSQ =  10
INTEGER(KIND=JPIM), PARAMETER :: NFBTEM   = 231
INTEGER(KIND=JPIM), PARAMETER :: NFBTEMSQ =  11
INTEGER(KIND=JPIM), PARAMETER :: NPILOT   =   6
INTEGER(KIND=JPIM), PARAMETER :: NPILOTSQ =   6
INTEGER(KIND=JPIM), PARAMETER :: NPILCT   =   7
INTEGER(KIND=JPIM), PARAMETER :: NLDPCD   =  32
INTEGER(KIND=JPIM), PARAMETER :: NLDPCDSQ =   1
INTEGER(KIND=JPIM), PARAMETER :: NSHPCD   =  33
INTEGER(KIND=JPIM), PARAMETER :: NSHPCDSQ =   2
INTEGER(KIND=JPIM), PARAMETER :: NWPPCD   =  34
INTEGER(KIND=JPIM), PARAMETER :: NWPPCDSQ =   3
INTEGER(KIND=JPIM), PARAMETER :: NEWPPCD  = 134
INTEGER(KIND=JPIM), PARAMETER :: NEWPPCDSQ=   4
INTEGER(KIND=JPIM), PARAMETER :: NJWPPCD  = 131
INTEGER(KIND=JPIM), PARAMETER :: NJWPPCDSQ=   5
INTEGER(KIND=JPIM), PARAMETER :: NBLDPCD  = 112
INTEGER(KIND=JPIM), PARAMETER :: NBLDPCDSQ=   6
INTEGER(KIND=JPIM), PARAMETER :: NBSHPCD  = 113
INTEGER(KIND=JPIM), PARAMETER :: NBSHPCDSQ=   7
INTEGER(KIND=JPIM), PARAMETER :: NSATEM   =   7
INTEGER(KIND=JPIM), PARAMETER :: NSATEMSQ =   7
INTEGER(KIND=JPIM), PARAMETER :: NALLSKY  =  16
INTEGER(KIND=JPIM), PARAMETER :: NALLSKYSQ=  16
INTEGER(KIND=JPIM), PARAMETER :: NALLSKYCT=   1
INTEGER(KIND=JPIM), PARAMETER :: NSAMCT   =  13
INTEGER(KIND=JPIM), PARAMETER :: NSTMCD   =  86
INTEGER(KIND=JPIM), PARAMETER :: NSTMCDSQ =   1
INTEGER(KIND=JPIM), PARAMETER :: NSTOVS   = 186
INTEGER(KIND=JPIM), PARAMETER :: NSTOVSSQ =   2
INTEGER(KIND=JPIM), PARAMETER :: NSTRESAT = 206
INTEGER(KIND=JPIM), PARAMETER :: NSTRESATSQ =  11
INTEGER(KIND=JPIM), PARAMETER :: NSTDWL   = 185
INTEGER(KIND=JPIM), PARAMETER :: NSTDWLSQ =   3
INTEGER(KIND=JPIM), PARAMETER :: NSTTOV   = 184
INTEGER(KIND=JPIM), PARAMETER :: NSTTOVSQ =   4
INTEGER(KIND=JPIM), PARAMETER :: NGTSTB   = 200
INTEGER(KIND=JPIM), PARAMETER :: NGTSTBSQ =   5
INTEGER(KIND=JPIM), PARAMETER :: NGTST1   = 201
INTEGER(KIND=JPIM), PARAMETER :: NGTST1SQ =   6
INTEGER(KIND=JPIM), PARAMETER :: NGTST2   = 202
INTEGER(KIND=JPIM), PARAMETER :: NGTST2SQ =   7
INTEGER(KIND=JPIM), PARAMETER :: NGTHRB   = 210
INTEGER(KIND=JPIM), PARAMETER :: NGTHRBSQ =   8
INTEGER(KIND=JPIM), PARAMETER :: NGTHR1   = 211
INTEGER(KIND=JPIM), PARAMETER :: NGTHR1SQ =   9
INTEGER(KIND=JPIM), PARAMETER :: NGTHR2   = 212
INTEGER(KIND=JPIM), PARAMETER :: NGTHR2SQ =  10
INTEGER(KIND=JPIM), PARAMETER :: NSSMI    = 215
INTEGER(KIND=JPIM), PARAMETER :: NSSMISQ  =   1
INTEGER(KIND=JPIM), PARAMETER :: NPAOB    =   8
INTEGER(KIND=JPIM), PARAMETER :: NPAOBSQ  =   8
INTEGER(KIND=JPIM), PARAMETER :: NPAOCT   =   2
INTEGER(KIND=JPIM), PARAMETER :: NPABCD   = 180
INTEGER(KIND=JPIM), PARAMETER :: NPABCDSQ =   1
INTEGER(KIND=JPIM), PARAMETER :: NTYPHO   = 181
INTEGER(KIND=JPIM), PARAMETER :: NTYPHOSQ =   2
INTEGER(KIND=JPIM), PARAMETER :: NSCATT   =   9
INTEGER(KIND=JPIM), PARAMETER :: NSCATTSQ =   9
INTEGER(KIND=JPIM), PARAMETER :: NSCACT   =   6
INTEGER(KIND=JPIM), PARAMETER :: NSCAT1   =   8
INTEGER(KIND=JPIM), PARAMETER :: NSCAT1SQ =   1
INTEGER(KIND=JPIM), PARAMETER :: NSCAT2   = 122
INTEGER(KIND=JPIM), PARAMETER :: NSCAT2SQ =   2
INTEGER(KIND=JPIM), PARAMETER :: NSCAT3   = 139
INTEGER(KIND=JPIM), PARAMETER :: NSCAT3SQ =   3
INTEGER(KIND=JPIM), PARAMETER :: NSCAT4   = 300
INTEGER(KIND=JPIM), PARAMETER :: NSCAT4SQ =   4
INTEGER(KIND=JPIM), PARAMETER :: NSCAT5   = 301
INTEGER(KIND=JPIM), PARAMETER :: NSCAT5SQ =   5
INTEGER(KIND=JPIM), PARAMETER :: NSCAT6   = 302
INTEGER(KIND=JPIM), PARAMETER :: NSCAT6SQ =   6
INTEGER(KIND=JPIM), PARAMETER :: NSCAT7   = 303 
INTEGER(KIND=JPIM), PARAMETER :: NSCAT7SQ =   7 
INTEGER(KIND=JPIM), PARAMETER :: NSCAT8   = 304 !GDC to update after launch
INTEGER(KIND=JPIM), PARAMETER :: NSCAT8SQ =   8 !GDC to update after launch
INTEGER(KIND=JPIM), PARAMETER :: NLIMB    =  10
INTEGER(KIND=JPIM), PARAMETER :: NLIMBSQ  =  10
INTEGER(KIND=JPIM), PARAMETER :: NLIMBCT  =   2
INTEGER(KIND=JPIM), PARAMETER :: NRALT    =  12
INTEGER(KIND=JPIM), PARAMETER :: NRALTSQ  =  12
INTEGER(KIND=JPIM), PARAMETER :: NRALTCT  =   5
INTEGER(KIND=JPIM), PARAMETER :: NRALT1   = 123
INTEGER(KIND=JPIM), PARAMETER :: NRALT1SQ =   1
INTEGER(KIND=JPIM), PARAMETER :: NRALT2   = 213
INTEGER(KIND=JPIM), PARAMETER :: NRALT2SQ =   2
INTEGER(KIND=JPIM), PARAMETER :: NRALT3   = 214
INTEGER(KIND=JPIM), PARAMETER :: NRALT3SQ =   3
INTEGER(KIND=JPIM), PARAMETER :: NRALT4   = 216
INTEGER(KIND=JPIM), PARAMETER :: NRALT4SQ =   4
INTEGER(KIND=JPIM), PARAMETER :: NRALT5   = 217
INTEGER(KIND=JPIM), PARAMETER :: NRALT5SQ =   5
INTEGER(KIND=JPIM), PARAMETER :: NGPSRO   = 250
INTEGER(KIND=JPIM), PARAMETER :: NGPSROSQ =   1
INTEGER(KIND=JPIM), PARAMETER :: NLRAD    = 251
INTEGER(KIND=JPIM), PARAMETER :: NLRADSQ  =   2
INTEGER(KIND=JPIM), PARAMETER :: NISAC    =  11
INTEGER(KIND=JPIM), PARAMETER :: NISACSQ  =  11
INTEGER(KIND=JPIM), PARAMETER :: NISACCT  =   1
INTEGER(KIND=JPIM), PARAMETER :: NISAC1   =   1
INTEGER(KIND=JPIM), PARAMETER :: NISAC1SQ =   1
INTEGER(KIND=JPIM), PARAMETER :: NRADAR   =  13
INTEGER(KIND=JPIM), PARAMETER :: NRADARSQ =  13
INTEGER(KIND=JPIM), PARAMETER :: NRDRCT   =   1
INTEGER(KIND=JPIM), PARAMETER :: NRADA1   =   2
INTEGER(KIND=JPIM), PARAMETER :: NRADA1SQ =   1
INTEGER(KIND=JPIM), PARAMETER :: NSMOS    = 400
INTEGER(KIND=JPIM), PARAMETER :: NSMOSSQ  =  12
INTEGER(KIND=JPIM), PARAMETER :: NTCWC    = 214
INTEGER(KIND=JPIM), PARAMETER :: NTCWCSQ  =  13
INTEGER(KIND=JPIM), PARAMETER :: NGBRAD   =  14
INTEGER(KIND=JPIM), PARAMETER :: NGBRADSQ =  14
INTEGER(KIND=JPIM), PARAMETER :: NGBRADCT =   1
INTEGER(KIND=JPIM), PARAMETER :: NRADRR   =   3
INTEGER(KIND=JPIM), PARAMETER :: NRADRRSQ =   1
INTEGER(KIND=JPIM), PARAMETER :: NLIDAR   =  15
INTEGER(KIND=JPIM), PARAMETER :: NLIDARSQ =  15
INTEGER(KIND=JPIM), PARAMETER :: NLIDARCT =   1
INTEGER(KIND=JPIM), PARAMETER :: NDWLPCD  = 187
INTEGER(KIND=JPIM), PARAMETER :: NDWLPCDSQ =  1
INTEGER(KIND=JPIM), PARAMETER :: NRAINGG  =  17
INTEGER(KIND=JPIM), PARAMETER :: NRAINGGSQ=  17
INTEGER(KIND=JPIM), PARAMETER :: NRAINGGCT=   1
INTEGER(KIND=JPIM), PARAMETER :: NIMSIMS  =  18
INTEGER(KIND=JPIM), PARAMETER :: NIMSIMSSQ=  18
INTEGER(KIND=JPIM), PARAMETER :: NIMSIMSCT=   1

INTEGER(KIND=JPIM), PARAMETER :: MSYNOP_SHIP_CODETYPES(5) = (/NSHSCD,NABSCD,NSHRED,NATSHS,NBSSCD/)
INTEGER(KIND=JPIM), PARAMETER :: MTEMP_SHIP_CODETYPES(2) = (/NSHTCD,NSBTEM/)
INTEGER(KIND=JPIM), PARAMETER :: MPILOT_SHIP_CODETYPES(2) = (/NSHPCD,NBSHPCD/)

INTEGER(KIND=JPIM), PARAMETER :: NMBPLT   = 132

INTEGER(KIND=JPIM), PARAMETER :: CCMO_LEN  = 32

CHARACTER(LEN=CCMO_LEN) :: CCMOOTP(JPNOTP) ! Names of observation types
INTEGER(KIND=JPIM) :: MNOCTP(JPNOTP)=-9999   ! Number of codetypes, per obs type
CHARACTER(LEN=CCMO_LEN) :: CCMOCTP(511)    ! Names of code types
INTEGER(KIND=JPIM) :: MSQBYCTP(511)=-9999    ! Converts from codetype to sequence No.

CONTAINS

SUBROUTINE SUCOCTP(KOUT)

!**** SUBROUTINE SUCOCTP - CMA OBSERVATION AND CODE TYPE

!        D. VASILJEVIC    ECMWF    01/09/1994

!**   PURPOSE
!     -------

!        SET CMA OBSERVATION AND CODE TYPES

!**   INTERFACE
!     ---------

!        CALL SUCOCTP(KOUT)
!     WHERE:
!            KOUT = OUTPUT UNIT

!        SUCOCTP IS CALLED BY

!**   METHOD
!     ------

!        CMA OBS. AND CODE TYPES ARE DEFINED.
!        NOTE that CODE TYPES have to be no bigger than 511.

!**   EXTERNALS
!     ---------

!        NONE

!**   MODIFICATIONS
!     -------------
!     23-12-2004 : RARAD becomes LIMB; new codetypes for LIMB
!     14-Mar-05  : D. Tan: Introduce Aeolus information
!     27-04-2009 : J Muñoz Sabater: new obs and code types for SMOS data
!     04-02-2009 : P. Lopez: new obstype and codetype for RADAR rain composites.
!     31-03-2010 : A Fouilloux: new codetype for MERIS
!     03/06/2011 : M. Rennie New obs type for LIDAR, with DWL code type moved to
!                  LIDAR
!     28/01/2014 : T. Kral   New codetypes for TAMDAR, ACARS with mixing ratio,
!                  BUFR PILOT and BUFR SYNOP
!-------------------------------------------------------------------------------

USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE YOMCMA   , ONLY : NMXOTP   ,NMXOCT

IMPLICIT NONE

INTEGER(KIND=JPIM),INTENT(IN)    :: KOUT
REAL(KIND=JPRB) :: ZHOOK_HANDLE

#include "abortdb.intfb.h"

IF (LHOOK) CALL DR_HOOK('YOMCOCTP:SUCOCTP',0,ZHOOK_HANDLE)

!*          0.1    PRESET

!*          0.1.1  NO. OF CMA OBS. TYPES

IF(NOOBST > NMXOTP)           THEN
  WRITE(KOUT,'(''0ERROR IN SUBROUTINE SUCOCTP'')')
  WRITE(KOUT,'('' NO. OF CMA OBS. TYPES TOO LARGE'')')
  WRITE(KOUT,'('' NO. OF CMA OBS. TYPES    :'',I10)') NOOBST
  WRITE(KOUT,'('' MAX NO. OF CMA OBS. TYPES:'',I10)') NMXOTP
  CALL ABORTDB('SUCOCTP','NO. OF CMA OBS. TYPES TOO LARGE',NOOBST)
ENDIF

!*          0.1.2  NO. OF CMA OBS. CODE TYPES

IF(NOCODT > NMXOCT)           THEN
  WRITE(KOUT,'(''0ERROR IN SUBROUTINE SUCOCTP'')')
  WRITE(KOUT,'('' NO. OF CMA CODE TYPES TOO LARGE'')')
  WRITE(KOUT,'('' NO. OF CMA CODE TYPES    :'',I10)') NOCODT
  WRITE(KOUT,'('' MAX NO. OF CMA CODE TYPES:'',I10)') NMXOCT
  CALL ABORTDB('SUCOCTP','NO. OF CMA CODE TYPES TOO LARGE',NOCODT)
ENDIF

MSQBYCTP(:)=0
CCMOOTP(:)='                                '
CCMOCTP(:)='                                '
MNOCTP(:)=1

!-----------------------------------------------------------------------

!        1.        CMA OBSERVATION AND CODE TYPES AND ASSOCIATED
!                  ---------------------------------------------
!                  SEQUENCE NO.
!                  ------------

!*          1.1    SYNOP

MNOCTP(NSYNOP)=NSYNCT
CCMOOTP(NSYNOP)='SYNOP, Land stations and ships  '

!*          1.1.1  SYNOP LAND REPORT

MSQBYCTP(NSRSCD)=NSRSCDSQ
CCMOCTP(NSRSCD)='SYNOP Land Manual Report               '

!*          1.1.2  SYNOP LAND AUTOMATIC REPORT

MSQBYCTP(NATSCD)=NATSCDSQ
CCMOCTP(NATSCD)='SYNOP Land Automatic Report     '

!*          1.1.3  SYNOP-SHIP REPORT

MSQBYCTP(NSHSCD)=NSHSCDSQ
CCMOCTP(NSHSCD)='SYNOP-SHIP Report               '

!*          1.1.4  SYNOP-SHIP ABBREVIATED REPORT

MSQBYCTP(NABSCD)=NABSCDSQ
CCMOCTP(NABSCD)='SYNOP-SHIP Abbreviated Report   '

!*          1.1.5  SYNOP SHRED REPORT

MSQBYCTP(NSHRED)=NSHREDSQ
CCMOCTP(NSHRED)='SYNOP SHRED Report              '

!*          1.1.6  SYNOP AUTOMATIC SHIP REPORT

MSQBYCTP(NATSHS)=NATSHSSQ
CCMOCTP(NATSHS)='SYNOP Automatic SHIP Report     '

!*          1.1.7  FRENCH SYNOP AUTOMATIC LAND REPORT

MSQBYCTP(NSYRCD)=NSYRCDSQ
CCMOCTP(NSYRCD)='French SYNOP Automatic Land Repo'

!*          1.1.8  FRENCH RADOME

MSQBYCTP(NRADOH)=NRADOHSQ
CCMOCTP(NRADOH)='French RADOME                   '

!*          1.1.9  SYNOP METAR

MSQBYCTP(NMETAR)=NMETARSQ
CCMOCTP(NMETAR)='SYNOP METAR                     '

!*          1.1.10 Ground-based GPS

MSQBYCTP(NPGPS)=NPGPSSQ
CCMOCTP(NPGPS)='Ground-based GPS                '

!*          1.1.11  ADDITIONAL LAND REPORT

MSQBYCTP(NADSCD)=NADSCDSQ
CCMOCTP(NADSCD)='Additional Land Report     '

!*          1.1.12  BUFR LAND SYNOP REPORT

MSQBYCTP(NBLSCD)=NBLSCDSQ
CCMOCTP(NBLSCD)='BUFR Land SYNOP Report                 '

!*          1.1.13  BUFR Ship SYNOP REPORT

MSQBYCTP(NBSSCD)=NBSSCDSQ
CCMOCTP(NBSSCD)='BUFR Ship SYNOP Report                 '

!*          1.2    AIREP

MNOCTP(NAIREP)=NAIRCT
CCMOOTP(NAIREP)='AIREP, Aircraft data            '

!*          1.2.1  AIRCRAFT REPORT

MSQBYCTP(NAIRCD)=NAIRCDSQ
CCMOCTP(NAIRCD)='AIREP Aircraft Report           '

!*          1.2.2  CODAR REPORT

MSQBYCTP(NCODAR)=NCODARSQ
CCMOCTP(NCODAR)='CODAR Aircraft Report           '

!*          1.2.3  COLBA REPORT

MSQBYCTP(NCOLBA)=NCOLBASQ
CCMOCTP(NCOLBA)='COLBA Aircraft Report           '

!*          1.2.4  AMDAR AIRCRAFT REPORT

MSQBYCTP(NAMDAR)=NAMDARSQ
CCMOCTP(NAMDAR)='AMDAR Aircraft Report           '

!*          1.2.5  ACARS AIRCRAFT REPORT

MSQBYCTP(NACARS)=NACARSSQ
CCMOCTP(NACARS)='ACARS Aircraft Report           '

!*          1.2.6  SIMULATED AIREP REPORT

MSQBYCTP(NSIMAI)=NSIMAISQ
CCMOCTP(NSIMAI)='Simulated AIREP Report          '

!*          1.2.7  TAMDAR AIRCRAFT REPORT

MSQBYCTP(NTAMDAR)=NTAMDARSQ
CCMOCTP(NTAMDAR)='TAMDAR Aircraft Report           '

!*          1.2.8  ACARS WITH MIXING RATIO

MSQBYCTP(NACARSMR)=NACARSMRSQ
CCMOCTP(NACARSMR)='ACARS with Mixing Ratio         '

!*          1.2.9  WIGOS AMDAR AIRCRAFT REPORT

MSQBYCTP(NWAMDAR)=NWAMDARSQ
CCMOCTP(NWAMDAR)='WIGOS AMDAR Aircraft Report     '

!*          1.2.10  MODE-S EHS OBSERVATION

MSQBYCTP(NMDEHS)=NMDEHSSQ
CCMOCTP(NMDEHS)='Mode-S EHS Aircraft Report      '

!*          1.2.11  ADS-C AIRCRAFT REPORT

MSQBYCTP(NAADSC)=NAADSCSQ
CCMOCTP(NAADSC)='ADS-C Aircraft Report           '

!*          1.3    SATOB

MNOCTP(NSATOB)=NSABCT
CCMOOTP(NSATOB)='SATOB, Atmospheric motion winds '

!*          1.3.1  SATOB REPORT

MSQBYCTP(NSTBCD)=NSTBCDSQ
CCMOCTP(NSTBCD)='SATOB REPORT                    '

!*          1.3.2  HIGH RES. VIS WIND SATOB REPORT

MSQBYCTP(NSTB86)=NSTB86SQ
CCMOCTP(NSTB86)='High Res. Vis Wind SATOB Report '

!*          1.3.3  SST REPORT

MSQBYCTP(NSST)=NSSTSQ
CCMOCTP(NSST)='SST Report                      '

!*          1.3.4  AMV SATOB REPORT

MSQBYCTP(NSTB87)=NSTB87SQ
CCMOCTP(NSTB87)='SATOB Atmospheric Motion Vector '

!*          1.4    DRIBU

MNOCTP(NDRIBU)=NDRICT
CCMOOTP(NDRIBU)='DRIBU, Drifing Buoys            '

!*          1.4.1  DRIBU REPORT

MSQBYCTP(NDRBCD)=NDRBCDSQ
CCMOCTP(NDRBCD)='DRIBU Buoy Report               '

!*          1.4.2  BATHY REPORT

MSQBYCTP(NBATHY)=NBATHYSQ
CCMOCTP(NBATHY)='BATHY Buoy Report               '

!*          1.4.3  TESAC REPORT

MSQBYCTP(NTESAC)=NTESACSQ
CCMOCTP(NTESAC)='TESAC Buoy Report               '

!*          1.4.4  ERS1 AS DRIBU

MSQBYCTP(NDERS1)=NDERS1SQ
CCMOCTP(NDERS1)='ERS1 as DRIBU                   '

!*          1.4.5  Moored Buoy Report

MSQBYCTP(NBUOYM)=NBUOYMSQ
CCMOCTP(NBUOYM)='Moored Buoy Report              '

!*          1.4.6  Drifting Buoy Report

MSQBYCTP(NBUOYD)=NBUOYDSQ
CCMOCTP(NBUOYD)='Drifting Buoy Report            '

!*          1.5    TEMP

MNOCTP(NTEMP)=NTEMCT
CCMOOTP(NTEMP )='TEMP,  Radiosondes              '

!*          1.5.1  LAND TEMP REPORT

MSQBYCTP(NLDTCD)=NLDTCDSQ
CCMOCTP(NLDTCD)='TEMP Land Report                '

!*          1.5.2  TEMP SHIP REPORT

MSQBYCTP(NSHTCD)=NSHTCDSQ
CCMOCTP(NSHTCD)='TEMP SHIP Report                '

!*          1.5.3  TEMP-DROP REPORT

MSQBYCTP(NTDROP)=NTDROPSQ
CCMOCTP(NTDROP)='TEMP Dropsonde Report           '

!*          1.5.4  ROCOB REPORT

MSQBYCTP(NROCOB)=NROCOBSQ
CCMOCTP(NROCOB)='ROCOB TEMP Rocket Report        '

!*          1.5.5  ROCOB SHIP REPORT

MSQBYCTP(NROCSH)=NROCSHSQ
CCMOCTP(NROCSH)='ROCOB SHIP Rocket Report        '

!*          1.5.6  MOBILE TEMP REPORT

MSQBYCTP(NMBTMP)=NMBTMPSQ
CCMOCTP(NMBTMP)='Mobile TEMP Report              '

!*          1.5.7  SIMULATED TEMP STATION CODE TYPE

MSQBYCTP(NSIMTE)=NSIMTESQ
CCMOCTP(NSIMTE)='Simulated TEMP Station Report   '

!*          1.5.8  BUFR Land TEMP

MSQBYCTP(NLBTEM)=NLBTEMSQ
CCMOCTP(NLBTEM)='BUFR Land TEMP                  '

!*          1.5.9  BUFR Ship TEMP

MSQBYCTP(NSBTEM)=NSBTEMSQ
CCMOCTP(NSBTEM)='BUFR Ship TEMP                  '

!*          1.5.10 BUFR TEMP DROP

MSQBYCTP(NDBTEM)=NDBTEMSQ
CCMOCTP(NDBTEM)='BUFR TEMP DROP                  '

!*          1.5.11 BUFR TEMP DESCENT

MSQBYCTP(NFBTEM)=NFBTEMSQ
CCMOCTP(NFBTEM)='BUFR TEMP DESCENT               '

!*          1.6    PILOT

MNOCTP(NPILOT)=NPILCT
CCMOOTP(NPILOT)='PILOT, Balloons and profilers   '

!*          1.6.1  LAND PILOT REPORT

MSQBYCTP(NLDPCD)=NLDPCDSQ
CCMOCTP(NLDPCD)='PILOT Land Report               '

!*          1.6.2  SHIP PILOT REPORT

MSQBYCTP(NSHPCD)=NSHPCDSQ
CCMOCTP(NSHPCD)='PILOT SHIP Report               '

!*          1.6.3  AMERICAN WIND PROFILERS

MSQBYCTP(NWPPCD)=NWPPCDSQ
CCMOCTP(NWPPCD)='American Wind Profiler          '

!*          1.6.4  EUROPEAN WIND PROFILERS

MSQBYCTP(NEWPPCD)=NEWPPCDSQ
CCMOCTP(NEWPPCD)='European Wind Profiler          '

!*          1.6.5  JAPANESE WIND PROFILERS

MSQBYCTP(NJWPPCD)=NJWPPCDSQ
CCMOCTP(NJWPPCD)='Japanese Wind Profiler          '

!*          1.6.6  BUFR LAND PILOT REPORT

MSQBYCTP(NBLDPCD)=NBLDPCDSQ
CCMOCTP(NBLDPCD)='BUFR PILOT Land Report               '

!*          1.6.7  BUFR SHIP PILOT REPORT

MSQBYCTP(NBSHPCD)=NBSHPCDSQ
CCMOCTP(NBSHPCD)='BUFR PILOT SHIP Report               '

!*          1.6.6a  MOBILE WIND PILOT - OBSOLETE

!*          1.6.6b  DOPPLER WIND LIDAR

MSQBYCTP(NDWLPCD)=NDWLPCDSQ
CCMOCTP(NDWLPCD)='Doppler Wind Lidar              '

!*          1.7    SATEM

MNOCTP(NSATEM)=NSAMCT
CCMOOTP(NSATEM)='SATEM, Satellite sounding data  '

!*          1.7.1  SATEM REPORT

MSQBYCTP(NSTMCD)=NSTMCDSQ
CCMOCTP(NSTMCD)='SATEM REPORT                    '

!*          1.7.2  HIGH RESOLUTION SATELLITE REPORT

MSQBYCTP(NSTOVS)=NSTOVSSQ
CCMOCTP(NSTOVS)='High Resolution Sattelite Report'

!*          1.7.3  HIGH RESOLUTION SIMULATED DWL SATELLITE REPORT

MSQBYCTP(NSTDWL)=NSTDWLSQ
CCMOCTP(NSTDWL)='High Resolution Simulated DWL Re'

!*          1.7.4  HIGH RESOLUTION SIMULATED TOVS SATELLITE REPORT

MSQBYCTP(NSTTOV)=NSTTOVSQ
CCMOCTP(NSTTOV)='High Resolution Simulated TOVS R'

!*          1.7.5  GTS BUFR SATEM REPORT
!                  (250 KM TEMP AND HUM PROFILES)

MSQBYCTP(NGTSTB)=NGTSTBSQ
CCMOCTP(NGTSTB)='GTS BUFR 250 KM SATEM Report    '

!*          1.7.6  GTS BUFR SATEM CLEAR RADIANCE REPORT

MSQBYCTP(NGTST1)=NGTST1SQ
CCMOCTP(NGTST1)='GTS BUFR SATEM Clear Radiance Re'

!*          1.7.7  GTS BUFR SATEM RETR PROFILES AND
!                  CLEAR RADIANCES REPORT

MSQBYCTP(NGTST2)=NGTST2SQ
CCMOCTP(NGTST2)='GTS BUFR Retr. Prof. and Radianc'

!*          1.7.8  HIGH RES 80 KM BUFR NON GTS SATEM RETR PROFILES

MSQBYCTP(NGTHRB)=NGTHRBSQ
CCMOCTP(NGTHRB)='Level 1C Calibrated Radiances   '

!*          1.7.9  HIGH RES 80 KM BUFR NON GTS SATEM CLEAR
!                  RADIANCE REPORT

MSQBYCTP(NGTHR1)=NGTHR1SQ
CCMOCTP(NGTHR1)='Rtovs Clear Radiances and Retr. '

!*          1.7.10 HIGH RES 80 KM BUFR NON GTS SATEM PROFILES AND
!                  CLEAR RADIANCE REPORT

MSQBYCTP(NGTHR2)=NGTHR2SQ
CCMOCTP(NGTHR2)='TOVS Clear Radiances and Retr.  '

!*          1.7.12 RETRIEVED OZONE LAYERS REPORT

MSQBYCTP(NSTRESAT)=NSTRESATSQ
CCMOCTP(NSTRESAT)='Retrieved ozone layers report  '

!*          1.7.13 SMOS L-band radiances

MSQBYCTP(NSMOS)=NSMOSSQ
CCMOCTP(NSMOS)='SMOS level 1C L-band radiances  '

!*          1.7.14 MERIS REPORT

MSQBYCTP(NTCWC)= NTCWCSQ
CCMOCTP(NTCWC)='TCWC (MERIS) Report                   '

!*          1.8    PAOB

MNOCTP(NPAOB)=NPAOCT
CCMOOTP(NPAOB )='PAOB,  Australian pseudo obs    '

!*          1.8.1  PAOB REPORT

MSQBYCTP(NPABCD)=NPABCDSQ
CCMOCTP(NPABCD)='PAOB Report                     '

!*          1.8.2  Donnees cyclone reunion

MSQBYCTP(NTYPHO)=NTYPHOSQ
CCMOCTP(NTYPHO)='TYPHO Report                     '

!*          1.9    SCATTEROMETER

MNOCTP(NSCATT)=NSCACT
CCMOOTP(NSCATT)='SCATT, Scatterometer            '

!*          1.9.1  SCATTEROMETER 1 (Obsolete)

MSQBYCTP(NSCAT1)=NSCAT1SQ
CCMOCTP(NSCAT1)='ERS Scatterometer 1 (old)       '

!*          1.9.2  SCATTEROMETER 2

MSQBYCTP(NSCAT2)=NSCAT2SQ
CCMOCTP(NSCAT2)='ERS Scatterometer               '

!*          1.9.3  SCATTEROMETER 3

MSQBYCTP(NSCAT3)=NSCAT3SQ
CCMOCTP(NSCAT3)='ASCAT Scatterometer             '

!*          1.9.4  SCATTEROMETER 4

MSQBYCTP(NSCAT4)=NSCAT4SQ
CCMOCTP(NSCAT4)='NSCAT ADEOS-1                   '

!*          1.9.5  SCATTEROMETER 5

MSQBYCTP(NSCAT5)=NSCAT5SQ
CCMOCTP(NSCAT5)='QuikSCAT                        '

!*          1.9.6  SCATTEROMETER 6

MSQBYCTP(NSCAT6)=NSCAT6SQ
CCMOCTP(NSCAT6)='Ku-band Scatterometers (OSCAT/RSCAT/HSCAT/SSCAT) '

!*          1.9.7  SCATTEROMETER 7

MSQBYCTP(NSCAT7)=NSCAT7SQ
CCMOCTP(NSCAT7)='CFOSAT Scatterometer                        '

!*          1.9.8  SCATTEROMETER 8

MSQBYCTP(NSCAT8)=NSCAT8SQ
CCMOCTP(NSCAT8)='FY-3Y WindRAD Scatterometers  '


!*          1.10   Limb observations

MNOCTP(NLIMB)=NLIMBCT
CCMOOTP(NLIMB)='LIMB, Limb observations        '

!*          1.10.1 GPS Radio occultation

MSQBYCTP(NGPSRO)=NGPSROSQ
CCMOCTP(NGPSRO)='GPS Radio occultation           '

!*          1.10.2 Limb radiances

MSQBYCTP(NLRAD)=NLRADSQ
CCMOCTP(NLRAD)='Limb radiances                  '

!*          1.11    ISAC

MNOCTP(NISAC)=NISACCT
CCMOOTP(NISAC)='ISAC, in-situ atm. composition  '

!*          1.11.1 IAGOS aircraft data

MSQBYCTP(NISAC1)=NISAC1SQ
CCMOCTP(NISAC1)='IAGOS aircraft data             '

!*          1.12   RADAR ALTIMETER

MNOCTP(NRALT)=NRALTCT
CCMOOTP(NRALT)='RALT, Radar Altimeter           '

!*          1.12.1 RADAR ALTIMETER (ERS-1/2)

MSQBYCTP(NRALT1)=NRALT1SQ
CCMOCTP(NRALT1)='ERS-1/2 Radar Altimeter         '

!*          1.12.2 RADAR ALTIMETER (ENVISAT)

MSQBYCTP(NRALT2)=NRALT2SQ
CCMOCTP(NRALT2)='ENVISAT Radar Altimeter         '

!*          1.12.3 RADAR ALTIMETER (Jason-1)

MSQBYCTP(NRALT3)=NRALT3SQ
CCMOCTP(NRALT3)='Jason-1 Radar Altimeter         '

!*          1.12.4 RADAR ALTIMETER (Jason-2)

MSQBYCTP(NRALT4)=NRALT4SQ
CCMOCTP(NRALT4)='Jason-2 Radar Altimeter         '

!*          1.12.5 RADAR ALTIMETER (CryoSat-2)

MSQBYCTP(NRALT5)=NRALT5SQ
CCMOCTP(NRALT5)='CryoSat-2 Radar Altimeter       '

!*          1.13   RADAR

MNOCTP(NRADAR)=NRDRCT
CCMOOTP(NRADAR)='RADAR, meteorological radar     '

!*          1.13.1 BUFR RADAR REFLECTIVITY 1

MSQBYCTP(NRADA1)=NRADA1SQ
CCMOCTP(NRADA1)='RARAD 1                         '

!*          1.14   GROUND-BASED RADAR PRECIPITATION COMPOSITES (ECMWF)

MNOCTP(NGBRAD)=NGBRADCT
CCMOOTP(NGBRAD)='Ground-based precip composites  '

!*          1.14.1 BUFR GROUND-BASED RADAR RAIN RATE (ECMWF)

MSQBYCTP(NRADRR)=NRADRRSQ
CCMOCTP(NRADRR)='RADAR RAIN RATE                 '

!*          1.15   LIDAR observations

MNOCTP(NLIDAR)=NLIDARCT
CCMOOTP(NLIDAR)='LIDAR, Lidar observations        '

!*          1.15.1 Doppler wind lidar

MSQBYCTP(NDWLPCD)=NDWLPCDSQ
CCMOCTP(NDWLPCD)='Doppler Wind Lidar              '

!*          1.16  All-sky satellite radiances

MNOCTP(NALLSKY)=NALLSKYCT
CCMOOTP(NALLSKY)='All-sky satellite radiances     '

MSQBYCTP(NSSMI)=NSSMISQ
CCMOCTP(NSSMI)='SSMI or TRMM Report             '

!*          1.17   RAIN GAUGE DATA (ECMWF)

MNOCTP(NRAINGG)=NRAINGGCT
CCMOOTP(NRAINGG)='Rain gauge data                 '

!*          1.18   RADAR ALTIMETER
MNOCTP(NIMSIMS)=NIMSIMSCT
CCMOOTP(NIMSIMS)='IMS Report                      '

!*
!-----------------------------------------------------------------------

!        2.       SETUP DONE
!                 ----------

!     WRITE(KOUT,'(''0CMA OBS./CODE TYPES SETUP'')')
!*
!-----------------------------------------------------------------------

!        3.       RETURN
!                 ------

IF (LHOOK) CALL DR_HOOK('YOMCOCTP:SUCOCTP',1,ZHOOK_HANDLE)
END SUBROUTINE SUCOCTP
!-----------------------------------------------------------------------
END MODULE YOMCOCTP
