# Makefile created by mkmf $Id$ 

include ../../../build_templates/mkmf.template


.DEFAULT:
	-touch $@
all: fixsys obs_impact_tool
fixsys: 
	@ (cd ../../../assimilation_code/modules/utilities; ./fixsystem $(FC) )
types_mod.o: ../../../assimilation_code/modules/utilities/types_mod.f90
	$(FC) $(FFLAGS) $(OTHERFLAGS) -c	../../../assimilation_code/modules/utilities/types_mod.f90
parse_args_mod.o: ../../../assimilation_code/modules/utilities/parse_args_mod.f90 utilities_mod.o
	$(FC) $(FFLAGS) $(OTHERFLAGS) -c	../../../assimilation_code/modules/utilities/parse_args_mod.f90
obs_kind_mod.o: ../../../assimilation_code/modules/observations/obs_kind_mod.f90 types_mod.o utilities_mod.o
	$(FC) $(FFLAGS) $(OTHERFLAGS) -c	../../../assimilation_code/modules/observations/obs_kind_mod.f90
time_manager_mod.o: ../../../assimilation_code/modules/utilities/time_manager_mod.f90 types_mod.o utilities_mod.o
	$(FC) $(FFLAGS) $(OTHERFLAGS) -c	../../../assimilation_code/modules/utilities/time_manager_mod.f90
null_mpi_utilities_mod.o: ../../../assimilation_code/modules/utilities/null_mpi_utilities_mod.f90 types_mod.o utilities_mod.o time_manager_mod.o
	$(FC) $(FFLAGS) $(OTHERFLAGS) -c	../../../assimilation_code/modules/utilities/null_mpi_utilities_mod.f90
obs_impact_tool.o: ../../../assimilation_code/programs/obs_impact_tool/obs_impact_tool.f90 types_mod.o utilities_mod.o obs_impact_mod.o
	$(FC) $(FFLAGS) $(OTHERFLAGS) -c	../../../assimilation_code/programs/obs_impact_tool/obs_impact_tool.f90
utilities_mod.o: ../../../assimilation_code/modules/utilities/utilities_mod.f90 types_mod.o
	$(FC) $(FFLAGS) $(OTHERFLAGS) -c	../../../assimilation_code/modules/utilities/utilities_mod.f90
obs_impact_mod.o: ../../../assimilation_code/modules/utilities/obs_impact_mod.f90 types_mod.o utilities_mod.o obs_kind_mod.o parse_args_mod.o
	$(FC) $(FFLAGS) $(OTHERFLAGS) -c	../../../assimilation_code/modules/utilities/obs_impact_mod.f90
./null_mpi_utilities_mod.f90: ../../../assimilation_code/modules/utilities/null_mpi_utilities_mod.f90
	cp ../../../assimilation_code/modules/utilities/null_mpi_utilities_mod.f90 .
./time_manager_mod.f90: ../../../assimilation_code/modules/utilities/time_manager_mod.f90
	cp ../../../assimilation_code/modules/utilities/time_manager_mod.f90 .
./obs_impact_mod.f90: ../../../assimilation_code/modules/utilities/obs_impact_mod.f90
	cp ../../../assimilation_code/modules/utilities/obs_impact_mod.f90 .
./obs_impact_tool.f90: ../../../assimilation_code/programs/obs_impact_tool/obs_impact_tool.f90
	cp ../../../assimilation_code/programs/obs_impact_tool/obs_impact_tool.f90 .
./utilities_mod.f90: ../../../assimilation_code/modules/utilities/utilities_mod.f90
	cp ../../../assimilation_code/modules/utilities/utilities_mod.f90 .
./types_mod.f90: ../../../assimilation_code/modules/utilities/types_mod.f90
	cp ../../../assimilation_code/modules/utilities/types_mod.f90 .
./obs_kind_mod.f90: ../../../assimilation_code/modules/observations/obs_kind_mod.f90
	cp ../../../assimilation_code/modules/observations/obs_kind_mod.f90 .
./parse_args_mod.f90: ../../../assimilation_code/modules/utilities/parse_args_mod.f90
	cp ../../../assimilation_code/modules/utilities/parse_args_mod.f90 .
SRC = ../../../assimilation_code/modules/utilities/types_mod.f90 ../../../assimilation_code/modules/utilities/parse_args_mod.f90 ../../../assimilation_code/modules/observations/obs_kind_mod.f90 ../../../assimilation_code/modules/utilities/time_manager_mod.f90 ../../../assimilation_code/modules/utilities/null_mpi_utilities_mod.f90 ../../../assimilation_code/programs/obs_impact_tool/obs_impact_tool.f90 ../../../assimilation_code/modules/utilities/utilities_mod.f90 ../../../assimilation_code/modules/utilities/obs_impact_mod.f90
OBJ = types_mod.o parse_args_mod.o obs_kind_mod.o time_manager_mod.o null_mpi_utilities_mod.o obs_impact_tool.o utilities_mod.o obs_impact_mod.o
OFF = ../../../assimilation_code/modules/utilities/null_mpi_utilities_mod.f90 ../../../assimilation_code/modules/utilities/time_manager_mod.f90 ../../../assimilation_code/modules/utilities/obs_impact_mod.f90 ../../../assimilation_code/programs/obs_impact_tool/obs_impact_tool.f90 ../../../assimilation_code/modules/utilities/utilities_mod.f90 ../../../assimilation_code/modules/utilities/types_mod.f90 ../../../assimilation_code/modules/observations/obs_kind_mod.f90 ../../../assimilation_code/modules/utilities/parse_args_mod.f90
clean: neat
	-rm -f .cppdefs $(OBJ) obs_impact_tool
neat:
	-rm -f $(TMPFILES)
localize: $(OFF)
	cp $(OFF) .
TAGS: $(SRC)
	etags $(SRC)
tags: $(SRC)
	ctags $(SRC)
obs_impact_tool: $(OBJ)
	$(LD) $(OBJ) -o obs_impact_tool  $(LDFLAGS)
