INTERFACE
   SUBROUTINE BLACKBOX( &
        &     KOUT, KATEGORY, KPRINT, &
        &     KTEST_MDI, KFILL_FBVECTOR, &
        &     KCMBLI, ZCMCCC, &
        &     KFEEDBACK, KFEEDBACK_SIZE, &
        &     ZDATA, KDATA, KRETCODE)
     USE PARKIND, ONLY : JPIM,JPRD
     IMPLICIT NONE
     INTEGER(KIND=JPIM), INTENT(IN)  :: KOUT, KATEGORY, KPRINT, KTEST_MDI, KFILL_FBVECTOR
     INTEGER(KIND=JPIM), INTENT(OUT) :: KCMBLI
     REAL(KIND=JPRD),    INTENT(OUT) :: ZCMCCC
     INTEGER(KIND=JPIM), INTENT(IN)  :: KFEEDBACK_SIZE, KDATA
     INTEGER(KIND=JPIM), INTENT(OUT) :: KFEEDBACK(0:KFEEDBACK_SIZE)
     REAL(KIND=JPRD), INTENT(IN)     :: ZDATA(KDATA)
     INTEGER(KIND=JPIM), INTENT(OUT) :: KRETCODE
   END SUBROUTINE BLACKBOX
END INTERFACE
