INTERFACE
   SUBROUTINE BLACKBOX_INIT(KOUT, CDATA_NAME, KDATA, &
        &                         RMDI, &
        &                         KANDATE, KANTIME, &
        &                         KCOMPDATE, KCOMPTIME, &
        &                         KFEEDBACK_SIZE, KRETCODE)
     USE PARKIND, ONLY : JPIM, JPRD
     IMPLICIT NONE
     INTEGER(KIND=JPIM), INTENT(IN)       :: KOUT, KDATA
     REAL(KIND=JPRD), INTENT(IN)          :: RMDI
     CHARACTER(LEN=*), INTENT(IN)         :: CDATA_NAME(KDATA)
     INTEGER(KIND=JPIM),  INTENT(OUT)     :: KANDATE, KANTIME
     INTEGER(KIND=JPIM),  INTENT(OUT)     :: KCOMPDATE, KCOMPTIME
     INTEGER(KIND=JPIM),  INTENT(OUT)     :: KFEEDBACK_SIZE, KRETCODE
   END SUBROUTINE BLACKBOX_INIT
END INTERFACE
