!
! Automatically generated by ./mod_rw_for_rttov_types.pl
! Do not edit
!
! Copyright:
!    This software was developed within the context of
!    the EUMETSAT Satellite Application Facility on
!    Numerical Weather Prediction (NWP SAF), under the
!    Cooperation Agreement dated 25 November 1998, between
!    EUMETSAT and the Met Office, UK, by one or more partners
!    within the NWP SAF. The partners in the NWP SAF are
!    the Met Office, ECMWF, KNMI and MeteoFrance.
!
!    Copyright 2016, EUMETSAT, All Rights Reserved.
!
module rttov_hdf_pccomp_io
#include "throw.h"
use parkind1
!use rttov_print_mod
use rttov_hdf_mod
!use rttov_hdf_pccomp_def
!use rttov_hdf_pccomp_mem
use rttov_types

use hdf5
implicit none
#include "rttov_errorreport.interface"
private
public :: rttov_hdf_pccomp_init
public :: rttov_hdf_pccomp_rh
public :: rttov_hdf_pccomp_wh


contains


subroutine rttov_hdf_pccomp_init(x)
type(rttov_pccomp),intent(inout)::x

  nullify(x%PCSCORES)
  nullify(x%BT_PCCOMP)
  nullify(x%TOTAL_PCCOMP)
end subroutine

subroutine rttov_hdf_pccomp_rh(x,lun,err)
type(rttov_pccomp),intent(out)::x
integer(hid_t),intent(in)::lun
integer(kind=jpim),intent(out)::err
character(len=lensh)::sname
logical :: lext
TRY

call rttov_hdf_pccomp_init(x)

sname='PCSCORES'
call read_array_hdf(lun,sname,err,pr1=x%PCSCORES)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='BT_PCCOMP'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,pr1=x%BT_PCCOMP)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='TOTAL_PCCOMP'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,pr1=x%TOTAL_PCCOMP)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

err=0_jpim
CATCH
end subroutine

subroutine rttov_hdf_pccomp_wh(x,lun,err,compress,force_double)
type(rttov_pccomp),intent(in)::x
integer(hid_t),intent(in)::lun
integer(kind=jpim),intent(out)::err
logical,intent(in),optional::compress
logical,intent(in),optional::force_double
character(len=lensh)::sname

TRY
sname='PCSCORES'
if(associated(x%PCSCORES))then
  call write_array_hdf(lun,sname,&
    & 'Principal component scores (npcscores)',&
    & err,r1=x%PCSCORES , units = 'N/A'  )
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='BT_PCCOMP'
if(associated(x%BT_PCCOMP))then
  call write_array_hdf(lun,sname,&
    & 'Brightness temp equivalent to radiances reconstructed using principal components (nchannels_rec)',&
    & err,r1=x%BT_PCCOMP , units = 'K'  )
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='TOTAL_PCCOMP'
if(associated(x%TOTAL_PCCOMP))then
  call write_array_hdf(lun,sname,&
    & 'Radiances reconstructed using principal components (nchannels_rec)',&
    & err,r1=x%TOTAL_PCCOMP , units = 'mw/cm-1/ster/sq.m'  )
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

err=0_jpim
CATCH
end subroutine

end module
